Repository neo4j/docs-operations, pull requests merged in 2023-05, with the labels that each got.

#758 Updating command syntax after bug was flagged
  modules/ROOT/pages/backup-restore/offline-backup.adoc
Labels: bug, dev, cherry-pick-this-backward

#759 Updating command syntax after bug was flagged (#758)
  modules/ROOT/pages/backup-restore/offline-backup.adoc
Labels: cherry-picked, 5.x

#760 Update links to new Values and Types chapter in Cypher Manual
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, Cypher Manual Restructure

#763 Update links to new Values and Types chapter in Cypher Manual (#760)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#764 Update links to new Cypher Manual values and types chapter
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 4.4, cherry-picked, Cypher Manual Restructure

#659 Configure LDAP password through secret
  modules/ROOT/pages/kubernetes/configuration.adoc
Labels: 4.4, This branch only

#762 Removing link to backports as it is broken
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4, cherry-pick-this-backward

#747 Removing sentence as requested
  modules/ROOT/pages/clustering/internals.adoc
Labels: 4.4, cherry-pick-this-to-4.0

#766 Removing link to backports as it is broken (#762)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.2

#768 Removing link to backports as it is broken (#762)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.0

#770 fixed order on index page
  modules/ROOT/pages/clustering/clustering-advanced/index.adoc
Labels: cherry-pick-this-to-5.x, dev

#771 fixed order on index page (#770)
  modules/ROOT/pages/clustering/clustering-advanced/index.adoc
Labels: cherry-picked, 5.x

#750 Improve Configuration settings page
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/introduction.adoc
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/clustering/clustering-advanced/default-database.adoc
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/monitoring/endpoints.adoc
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/clustering/setup/routing.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/connectors.adoc
  modules/ROOT/pages/configuration/dynamic-settings.adoc
  modules/ROOT/pages/configuration/index.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/configuration/ports.adoc
  modules/ROOT/pages/configuration/transaction-logs.adoc
  modules/ROOT/pages/docker/configuration.adoc
  modules/ROOT/pages/docker/maintenance.adoc
  modules/ROOT/pages/docker/ref-settings.adoc
  modules/ROOT/pages/manage-databases/configuration.adoc
  modules/ROOT/pages/manage-databases/queries.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/monitoring/metrics/enable.adoc
  modules/ROOT/pages/monitoring/metrics/essential.adoc
  modules/ROOT/pages/monitoring/metrics/expose.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/monitoring/transaction-management.adoc
  modules/ROOT/pages/performance/bolt-thread-pool-configuration.adoc
  modules/ROOT/pages/performance/disks-ram-and-other-tips.adoc
  modules/ROOT/pages/performance/index-configuration.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/performance/statistics-execution-plans.adoc
  modules/ROOT/pages/reference/configuration-settings.adoc
  modules/ROOT/pages/reference/dynamic-settings-reference.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/routing-decisions.adoc
  modules/ROOT/pages/security/browser.adoc
  modules/ROOT/pages/security/checklist.adoc
  modules/ROOT/pages/security/securing-extensions.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
  modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-pick-this-to-5.x, 5.x, do not cherry-pick

#773 5.x config1
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/introduction.adoc
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/clustering/clustering-advanced/default-database.adoc
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/monitoring/endpoints.adoc
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/clustering/setup/routing.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/connectors.adoc
  modules/ROOT/pages/configuration/dynamic-settings.adoc
  modules/ROOT/pages/configuration/index.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/configuration/ports.adoc
  modules/ROOT/pages/configuration/transaction-logs.adoc
  modules/ROOT/pages/docker/configuration.adoc
  modules/ROOT/pages/docker/maintenance.adoc
  modules/ROOT/pages/docker/ref-settings.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/manage-databases/configuration.adoc
  modules/ROOT/pages/manage-databases/queries.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/monitoring/metrics/enable.adoc
  modules/ROOT/pages/monitoring/metrics/essential.adoc
  modules/ROOT/pages/monitoring/metrics/expose.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/monitoring/transaction-management.adoc
  modules/ROOT/pages/performance/bolt-thread-pool-configuration.adoc
  modules/ROOT/pages/performance/disks-ram-and-other-tips.adoc
  modules/ROOT/pages/performance/index-configuration.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/performance/statistics-execution-plans.adoc
  modules/ROOT/pages/reference/configuration-settings.adoc
  modules/ROOT/pages/reference/dynamic-settings-reference.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/routing-decisions.adoc
  modules/ROOT/pages/security/browser.adoc
  modules/ROOT/pages/security/checklist.adoc
  modules/ROOT/pages/security/securing-extensions.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
  modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked, 5.x

#774 removed section on connecting to a rr
  modules/ROOT/pages/clustering/deploy.adoc
Labels: cherry-pick-this-to-4.4, 4.2, cherry-pick-this-to-4.3, clustering

#775 4.3-cherry-pick-774
  modules/ROOT/pages/clustering/deploy.adoc
Labels: cherry-picked, 4.3, clustering

#776 reslved conflicts
  modules/ROOT/pages/clustering/deploy.adoc
Labels: 4.4, cherry-picked, clustering

#769 Store copy migration info
  modules/ROOT/pages/backup-restore/copy-database.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#782 Store copy migration info (#769)
  modules/ROOT/pages/backup-restore/copy-database.adoc
Labels: cherry-picked, 5.x

#783 Bump exact version to 4.4.20
  antora.yml
Labels: 4.4, This branch only

#778 Update ssl-framework.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#787 5.x release 5.8
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
Labels: cherry-picked, 5.x

#788 Update the version to 5.9
  antora.yml
Labels: dev, This branch only

#786 Update ssl-framework.adoc (#778)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, dev

#789 Add NODES 23 ad
  publish.yml
Labels: 5.x

#792 Defaults --strict option in import to false
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, 5.8

#790 Document db.logs.query.annotation_data_as_json_enabled
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.8

#794 Defaults --strict option in import to false (#792)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#795 Document db.logs.query.annotation_data_as_json_enabled (#790)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#798 dbms.setConfigValue must be used with bolt when in cluster
  modules/ROOT/pages/configuration/dynamic-settings.adoc
Labels: 4.4

#780 Polish server side routing information and settings.
  modules/ROOT/pages/clustering/internals.adoc
  modules/ROOT/partials/neo4j-config/all-settings.adoc
Labels: 4.4, This branch only

#779 Polish server side routing information.
  modules/ROOT/pages/clustering/setup/routing.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#801 Creating a database without specifying topology (#797)
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, 5.x

#793 Invalid NEO4J_PLUGINS values now produces a helpful error message
  modules/ROOT/pages/docker/operations.adoc
Labels: cherry-pick-this-to-5.x, 5.8

#804 Invalid NEO4J_PLUGINS values now produces a helpful error message (#793)
  modules/ROOT/pages/docker/operations.adoc
Labels: cherry-picked, 5.x

#803 Clarify that you should put all cluster members in list of discovery …
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x, clustering

#810 Update minimum value for minimum system primaries (#809)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x, clustering

#811 Bump exact version to 4.4.21
  antora.yml
Labels: 4.4, This branch only

#799 Remove reference to db.logs.query.time_logging
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.x, kernel

#814 remove reference to db.logs.query.time_logging
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#796 Deprecate upgrade procedures
  modules/ROOT/pages/reference/procedures.adoc
Labels: dev, 5.9

#815 fixed neoj4 <> neo4j typo in memory config docs
  modules/ROOT/pages/performance/memory-configuration.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#816 fixed neoj4 <> neo4j typo in memory config docs (#815)
  modules/ROOT/pages/performance/memory-configuration.adoc
Labels: cherry-picked, 5.x
