Repository neo4j/docs-operations, pull requests merged in 2023-06, with the labels that each got.

#800 Briefly describe each config group
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.x, kernel

#817 Briefly describe each config group (#800)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#805 Add compatibility guarantee for composite databases
  modules/ROOT/pages/composite-databases/index.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#820 Add compatibility guarantee for composite databases (#805)
  modules/ROOT/pages/composite-databases/index.adoc
Labels: cherry-picked, 5.x

#807 Write up how to deploy analytical clusters
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
Labels: cherry-pick-this-to-5.x, dev, clustering

#821 Write up how to deploy analytical clusters (#807)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
Labels: cherry-picked, 5.x, clustering

#818 Sync configuration settings with `SHOW SETTINGS` output
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#824 Fixes small typos and removes two leftovers
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#828 Update copy-database.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
Labels: cherry-pick-this forward, 5.x

#822 Add docs for logging group results from ldap server
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
Labels: cherry-pick-this forward, team-cypher-operations, 5.7

#831 Add docs for logging group results from ldap server (#822)
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
Labels: cherry-picked, dev

#832 Fix list formatting (#823)
  modules/ROOT/pages/installation/linux/debian.adoc
Labels: cherry-picked, dev

#819 Improve license acceptance wording
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#833 Improve license acceptance wording (#819)
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x

#827 Fixing 5.x settings names on 4.4 page
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: 4.4

#829 Add note about quoting in CREATE ALIAS and update examples to match
  modules/ROOT/pages/composite-databases/administration.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, 5.x

#834 Add new constraint types to intro table
  modules/ROOT/pages/introduction.adoc
Labels: dev, team-cypher-operations, 5.9

#839 Add new constraint types to intro table (#834)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked, 5.9

#841 Add note about quoting in CREATE ALIAS and update examples to match (…
  modules/ROOT/pages/composite-databases/administration.adoc
Labels: cherry-picked, 5.x

#761 Restructure the Кubernetes section
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/kubernetes/accessing-cluster.adoc
  modules/ROOT/pages/kubernetes/accessing-neo4j.adoc
  modules/ROOT/pages/kubernetes/authentication-authorization.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
  modules/ROOT/pages/kubernetes/import-data.adoc
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/monitoring.adoc
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/verify-cluster-formation.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/create-value-file.adoc
  modules/ROOT/pages/kubernetes/security.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#842 Restructure the Кubernetes section (#761)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/kubernetes/accessing-cluster.adoc
  modules/ROOT/pages/kubernetes/accessing-neo4j.adoc
  modules/ROOT/pages/kubernetes/authentication-authorization.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
  modules/ROOT/pages/kubernetes/import-data.adoc
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/monitoring.adoc
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/verify-cluster-formation.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/create-value-file.adoc
  modules/ROOT/pages/kubernetes/security.adoc
Labels: cherry-picked, 5.x

#845 Add collapse nested JSON objects in the query logger when db.logs.query.annotation_data_as_json_enabled setting is true
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#844 Update db.tx_log.rotation.retention_policy to include period-based transaction log pruning strategy with max size restriction
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.x, kernel

#846 Update db.tx_log.rotation.retention_policy to include period-based transaction log pruning strategy with max size restriction
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#836 Admonition message about the applicability of the option
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-pick-this forward, 5.x

#847 Admonition message about the applicability of the option (#836)
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, dev

#849 Split operations page into separate pages
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/import-data.adoc
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/maintenance.adoc
  modules/ROOT/pages/kubernetes/operations/assign-neo4j-pods.adoc
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
  modules/ROOT/pages/kubernetes/operations/dump-load.adoc
  modules/ROOT/pages/kubernetes/operations/image-pull-secret.adoc
  modules/ROOT/pages/kubernetes/operations/index.adoc
  modules/ROOT/pages/kubernetes/operations/maintenance-mode.adoc
  modules/ROOT/pages/kubernetes/operations/migrate-from-labs.adoc
  modules/ROOT/pages/kubernetes/operations/reset-password.adoc
  modules/ROOT/pages/kubernetes/operations/scaling.adoc
  modules/ROOT/pages/kubernetes/operations/upgrade.adoc
  modules/ROOT/pages/kubernetes/troubleshooting.adoc
Labels: cherry-pick-this-to-5.x, dev

#851 Mark incremental import as enterprise only
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: dev, 5.x, kernel

#840 Update Neo4j version
  antora.yml
Labels: 5.10

#850 Split operations page into separate pages (#849)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/import-data.adoc
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/maintenance.adoc
  modules/ROOT/pages/kubernetes/operations/assign-neo4j-pods.adoc
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
  modules/ROOT/pages/kubernetes/operations/dump-load.adoc
  modules/ROOT/pages/kubernetes/operations/image-pull-secret.adoc
  modules/ROOT/pages/kubernetes/operations/index.adoc
  modules/ROOT/pages/kubernetes/operations/maintenance-mode.adoc
  modules/ROOT/pages/kubernetes/operations/migrate-from-labs.adoc
  modules/ROOT/pages/kubernetes/operations/reset-password.adoc
  modules/ROOT/pages/kubernetes/operations/scaling.adoc
  modules/ROOT/pages/kubernetes/operations/upgrade.adoc
  modules/ROOT/pages/kubernetes/troubleshooting.adoc
Labels: cherry-picked, 5.x

#854 Add the neo4j-admin backup feature (#853)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#848 Adding 8.8 version of Red Hat in the list
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4

#785 Dev data consistency
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/index.adoc
  modules/ROOT/pages/configuration/transaction-logs.adoc
  modules/ROOT/pages/database-internals/checkpointing.adoc
  modules/ROOT/pages/database-internals/index.adoc
  modules/ROOT/pages/database-internals/locks-deadlocks.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/database-internals/transaction-management.adoc
  modules/ROOT/pages/monitoring/index.adoc
  modules/ROOT/pages/monitoring/metrics/essential.adoc
  modules/ROOT/pages/monitoring/query-management.adoc
  modules/ROOT/pages/monitoring/transaction-management.adoc
  modules/ROOT/pages/performance/disks-ram-and-other-tips.adoc
  modules/ROOT/pages/performance/index.adoc
  modules/ROOT/pages/performance/locks-deadlocks.adoc
  modules/ROOT/pages/performance/space-reuse.adoc
Labels: cherry-pick-this-to-5.x, 5.x, kernel

#855 Dev data consistency (#785)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/index.adoc
  modules/ROOT/pages/configuration/transaction-logs.adoc
  modules/ROOT/pages/database-internals/checkpointing.adoc
  modules/ROOT/pages/database-internals/index.adoc
  modules/ROOT/pages/database-internals/locks-deadlocks.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/database-internals/transaction-management.adoc
  modules/ROOT/pages/monitoring/index.adoc
  modules/ROOT/pages/monitoring/metrics/essential.adoc
  modules/ROOT/pages/monitoring/query-management.adoc
  modules/ROOT/pages/monitoring/transaction-management.adoc
  modules/ROOT/pages/performance/disks-ram-and-other-tips.adoc
  modules/ROOT/pages/performance/index.adoc
  modules/ROOT/pages/performance/locks-deadlocks.adoc
  modules/ROOT/pages/performance/space-reuse.adoc
Labels: cherry-picked, 5.x

#857 Add manage queries (#856)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/monitoring/index.adoc
  modules/ROOT/pages/monitoring/query-management.adoc
Labels: cherry-picked, 5.x

#858 Suggestion to improve code example to import database
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, dev

#835 Composite databases will not appear in requestedHosting
  modules/ROOT/pages/clustering/monitoring/show-servers-monitoring.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#861 Composite databases will not appear in requestedHosting (#835)
  modules/ROOT/pages/clustering/monitoring/show-servers-monitoring.adoc
Labels: cherry-picked

#862 4.4 backup helm
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/import-data.adoc
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/maintenance.adoc
  modules/ROOT/pages/kubernetes/operations/assign-neo4j-pods.adoc
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
  modules/ROOT/pages/kubernetes/operations/dump-load.adoc
  modules/ROOT/pages/kubernetes/operations/image-pull-secret.adoc
  modules/ROOT/pages/kubernetes/operations/index.adoc
  modules/ROOT/pages/kubernetes/operations/maintenance-mode.adoc
  modules/ROOT/pages/kubernetes/operations/migrate-from-labs.adoc
  modules/ROOT/pages/kubernetes/operations/reset-password.adoc
  modules/ROOT/pages/kubernetes/operations/scaling.adoc
  modules/ROOT/pages/kubernetes/operations/upgrade.adoc
  modules/ROOT/pages/kubernetes/troubleshooting.adoc
Labels: 4.4, This branch only

#865 Reword the warning about the use of the incremental import
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#868 Reword the warning about the use of the incremental import (#865)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#859 Improvements to the neo4j-admin copy documentation
  modules/ROOT/pages/backup-restore/copy-database.adoc
Labels: 4.4, cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, 5.x, kernel

#871 Update apoc plugin information
  modules/ROOT/pages/docker/operations.adoc
Labels: cherry-pick-this-to-5.x

#872 Update apoc plugin information
  modules/ROOT/pages/docker/operations.adoc
Labels: 4.4

#873 Update apoc plugin information
  modules/ROOT/pages/docker/operations.adoc
Labels: cherry-picked, 5.x

#863 Page on installing plugins to Neo4j
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/plugins.adoc
Labels: dev, cherry-pick-this-backward

#881 Page on installing plugins to Neo4j #863
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 4.2

#880 Page on installing plugins to Neo4j (#863)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 4.3

#882 Page on installing plugins to Neo4j #863
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 4.1

#883 Page on installing plugins to Neo4j #863
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 4.0

#866 Add a page about the reconciler pattern in a clustered DBMS
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/clustering-advanced/default-database.adoc
  modules/ROOT/pages/clustering/clustering-advanced/index.adoc
  modules/ROOT/pages/clustering/clustering-advanced/reconciler.adoc
Labels: cherry-picked, 5.x

#867 Add client-side routing section to cluster routing page
  modules/ROOT/pages/clustering/setup/routing.adoc
Labels: cherry-picked, 5.x
