Repository neo4j/docs-operations, pull requests merged in 2023-11, with the labels that each got.

#1162 update the version to 4.4.27
  antora.yml
Labels: 4.4

#1171 Remove test-skip anotations for cdc docs (#1167)
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: cherry-picked, 5.x

#1159 Adding description related to composite databases
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: cherry-pick-this-to-5.x, dev

#1172 Adding description related to composite databases (#1159)
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: cherry-picked, 5.x

#1173 fix redhat jdk version
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4

#1174 Alias for page causing 404
  modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc
  modules/ROOT/pages/database-administration/index.adoc
Labels: bug, cherry-pick-this-to-5.x, dev

#1176 Correct max label id
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
Labels: cherry-pick-this-to-5.x, dev, kernel

#1179 Correct max label id (#1176)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
Labels: cherry-picked, 5.x

#1180 Correct max label id (#1176)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
Labels: 4.4, cherry-picked

#1116 added note about clearing yum cache on upgrade
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: 4.4

#967 Add the deallocated server state
  modules/ROOT/images/server-states3.png
  modules/ROOT/pages/clustering/monitoring/show-servers-monitoring.adoc
  modules/ROOT/pages/clustering/servers.adoc
Labels: dev, 5.15

#1115 added note about clearing yum cache on upgrade
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-pick-this-to-5.x

#1182 added note about clearing yum cache on upgrade (#1115)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, 5.x

#1184 Updating information about netty files after neo4j 5.12 (#1178)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1155 Update procedures descriptions and modes according to the test results
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1188 bump exact version
  antora.yml
Labels: 4.4, do not cherry-pick

#1177 Improvement of instructions for SSL configuration
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: dev, cherry-pick-this-backward

#1189 Improvement of instructions for SSL configuration (#1177)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, cherry-pick-this-to-5.x

#1190 Improvement of instructions for SSL configuration (#1177)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4, cherry-picked

#1186 Update procedures descriptions and modes according to the test result…
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked

#1192 add support for Java 21
  modules/ROOT/pages/installation/requirements.adoc
Labels: 5.14

#1194 Docker - ref-settings.adoc: NEO4J_dbms_security_ldap_host typo error
  modules/ROOT/pages/docker/ref-settings.adoc
Labels: cherry-picked, dev

#1196 fix a typo in k8s
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
Labels: cherry-pick-this-to-5.x

#1197 fix a typo in k8s (#1196)
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
Labels: cherry-picked, 5.x

#1187 Updating the name of Azure Active Directory to Microsoft Entra ID
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: dev, team-cypher-operations, cherry-pick-this-backward

#1200 Updating the name of Azure Active Directory to Microsoft Entra ID (#1…
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked, 5.x

#1183 Improve documentation for suspended users
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, team-cypher-operations

#1201 Cherry-picks all 5.14 features from dev
  antora.yml
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#1202 Improve documentation for suspended users (#1183)
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
Labels: cherry-picked, 5.x

#1198 Add connections ad
  publish.yml
Labels: 5.x

#1205 Udate metrics according to the test results (#1195)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1207 Document using `Home` and `End` keys in Cypher Shell (#1161)
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: 4.4, cherry-picked

#1204 Updating the name of Azure Active Directory to Microsoft Entra ID (#1…
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: 4.4, cherry-picked

#1208 Fixing path to neo4j.config
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: dev, cherry-pick-this-backward

#1210 Fixing path to neo4j.config (#1208)
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked, 5.x

#1209 Add support for MinIO
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x, 5.14

#1219 Add support for MinIO
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#1220 Add support for MinIO
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: 4.4, cherry-picked

#1216 Update descriptions of metrics according to the test results
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: WIP, kernel, clustering

#1217 Neo4-admin-backup-globbing
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-pick-this forward, 5.x, 5.14
