Repository neo4j/docs-operations, pull requests merged in 2023-09, with the labels that each got.

#1018 5.x-cherry-pick-1015
  modules/ROOT/pages/clustering/monitoring/show-databases-monitoring.adoc
Labels: cherry-picked, clustering

#1001 Add labels `Dynamic` and `Deprecated` to config.settings
  modules/ROOT/pages/configuration/dynamic-settings.adoc
  modules/ROOT/partials/neo4j-config/all-settings.adoc
Labels: 4.4, do not cherry-pick

#1019 Update descriptions of `db.labels` and `db.relationshipTypes`
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, WIP, dev

#1021 Update descriptions of `db.labels` and `db.relationshipTypes` (#1019)
  modules/ROOT/pages/reference/procedures.adoc
Labels: 4.4, cherry-picked

#1023 Add support for affinity and tolerations
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x, 5.11

#1025 Add support for affinity and tolerations (#1023)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#1026 Add apoc.jdbc.<alias>.url and apoc.es.<key>.url in helm charts
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
Labels: cherry-pick-this-to-5.x, 5.11

#1024 Add support for affinity and tolerations
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: 4.4

#1029 Add apoc.jdbc.<alias>.url and apoc.es.<key>.url in helm charts
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
Labels: cherry-pick-this-to-5.x, 5.11

#1022 Update cypher-shell.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: cherry-pick-this-to-5.x

#1031 Add apoc.jdbc.<alias>.url and apoc.es.<key>.url in helm charts (#1029)
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
Labels: cherry-picked, 5.x

#1030 Add apoc.jdbc.<alias>.url and apoc.es.<key>.url in helm charts and missing support for PVC labels
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
Labels: 4.4

#826 Migrate Database Management and Alias management pages from Cypher Manual to Operations Manual
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
  modules/ROOT/pages/composite-databases/administration.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/configuration/password-and-user-recovery.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
  modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/sharding-with-copy.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/database-administration/queries.adoc
  modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/manage-databases/index.adoc
  modules/ROOT/pages/manage-databases/introduction.adoc
  modules/ROOT/pages/routing-decisions.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: Cypher Manual Restructure

#998 Add minor version to all features introduced in 5.x
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/reference/procedures.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
Labels: cherry-pick-this-to-5.x

#1033 Move config.settings to a new location under Configuration
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/reference/configuration-settings.adoc
  modules/ROOT/pages/reference/index.adoc
Labels: 4.4, This branch only

#973 Restructured Docker section and added documentation about mount points and plugins
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/plugins.adoc
  modules/ROOT/pages/docker/backup-restore.adoc
  modules/ROOT/pages/docker/configuration.adoc
  modules/ROOT/pages/docker/dump-load.adoc
  modules/ROOT/pages/docker/index.adoc
  modules/ROOT/pages/docker/introduction.adoc
  modules/ROOT/pages/docker/mounting-volumes.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/docker/plugins.adoc
  modules/ROOT/pages/docker/security.adoc
Labels: cherry-pick-this-to-5.x

#1035 Restructured Docker section and added documentation about mount points and plugins (#973)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/plugins.adoc
  modules/ROOT/pages/docker/backup-restore.adoc
  modules/ROOT/pages/docker/configuration.adoc
  modules/ROOT/pages/docker/dump-load.adoc
  modules/ROOT/pages/docker/index.adoc
  modules/ROOT/pages/docker/introduction.adoc
  modules/ROOT/pages/docker/mounting-volumes.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/docker/plugins.adoc
  modules/ROOT/pages/docker/security.adoc
Labels: cherry-picked, 5.x

#1037 Shortening titles for better SEO (#1036)
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/kubernetes/multi-dc-cluster/aks.adoc
  modules/ROOT/pages/kubernetes/operations/migrate-from-labs.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/uninstall-cleanup.adoc
Labels: cherry-picked, 5.x

#1038 Shortening titles for better SEO (#1036)
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/kubernetes/multi-dc-cluster/aks.adoc
  modules/ROOT/pages/kubernetes/operations/migrate-from-labs.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/uninstall-cleanup.adoc
Labels: 4.4, cherry-picked

#1039 Replace `db.logs.query.annotation_data_as_json_enabled` with `db.logsquery.annotation_data_format` to allow for more formats
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/dynamic-settings.adoc
  modules/ROOT/pages/docker/ref-settings.adoc
Labels: 5.12

#1041 Update Neo4j version to 5.13
  antora.yml
Labels: 5.13

#1040 Fix the failing tests
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-5.x

#1043 Fix the failing tests (#1040)
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-picked, 5.x

#1044 Update procedures and functions signatures
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.13

#1045 rearranged to accommodate all possible database states
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/monitoring/show-databases-monitoring.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: dev, do not cherry-pick

#1042 Add CDC Procedure descriptions
  modules/ROOT/pages/reference/procedures.adoc
Labels: team-cypher-operations, 5.13

#1046 Add default `LOAD ON ALL DATA` privilege to built-in roles
  modules/ROOT/pages/authentication-authorization/access-control.adoc
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
Labels: team-cypher-operations, 5.13

#1051 Add reverse-proxy
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/reverse-proxy.svg
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/accessing-neo4j.adoc
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
  modules/ROOT/pages/kubernetes/index.adoc
Labels: 5.12

#1052 Add reverse-proxy (#1051)
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/reverse-proxy.svg
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/accessing-neo4j.adoc
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
  modules/ROOT/pages/kubernetes/index.adoc
Labels: cherry-pick-this-to-5.x

#1054 Add reverse proxy
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/reverse-proxy.svg
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
  modules/ROOT/pages/kubernetes/index.adoc
Labels: 4.4

#1053 Update the available Neo4j Helm charts
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
Labels: cherry-pick-this-to-5.x, 5.12

#1055 Update the available Neo4j Helm charts (#1053)
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
Labels: cherry-picked, 5.x

#1050 Align default binding timeout
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, dev

#1056 Align default binding timeout (#1050)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1059 update exact version
  antora.yml
Labels: 4.4

#1057 Update the helm charts to 4.4.26
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
Labels: 4.4

#1058 Update the available helm charts
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
Labels: cherry-pick-this-to-5.x

#1049 Group configuration settings
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 4.4
