Repository neo4j/docs-operations, pull requests merged in 2023-03, with the labels that each got.

#630 Replace dbms.cluster.discovery.type setting with ~.resolver_type
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/docker/ref-settings.adoc
  modules/ROOT/pages/kubernetes/multi-dc-cluster/aks.adoc
  modules/ROOT/pages/reference/configuration-settings.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: 5.7, do not cherry-pick

#632 Fix the table Available commands per category
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#637 Fix the table Available commands per category
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
Labels: cherry-picked, 5.x

#638 Remove sharded and federated composite dbs
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked, 5.x
