Repository neo4j/docs-operations, pull requests merged in 2023-10, with the labels that each got.

#1069 update bolt metrics list
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: do not cherry-pick, 5.13

#1066 Add load privileges
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax_load_privileges.svg
  modules/ROOT/images/privileges_on_graph_syntax.svg
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
Labels: 5.13

#1070 Fix label misplacement
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1067 Incorporating the content from Alter database options #735
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: 5.13

#1068 Port content from the cypher manual #733
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/manage-execute-permissions.adoc
Labels: cherry-pick-this-to-5.x

#1063 Update procedures with new set procedure and beta status
  modules/ROOT/pages/reference/procedures.adoc
Labels: dev, 5.13

#1074 added rhel 9.2 support to list and improved instructions around non-interactive rpm installation
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4, cherry-pick-this-to-5.x

#1075 added rhel 9.2 support to list and improved instructions around non-i…
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#1048 Clarify system database role in seeding
  modules/ROOT/pages/clustering/seed.adoc
Labels: 4.4

#1073 Update note about needed privileges for @admin procedures on the procedures page
  modules/ROOT/pages/reference/procedures.adoc
Labels: team-cypher-operations, 5.13

#1061 added additional step to set NEO4J_PLUGINS env
  modules/ROOT/pages/kubernetes/plugins.adoc
Labels: cherry-pick-this-to-5.x

#1077 Add temporal and size parameters for `db.tx_log.rotation.retention_policy`
  modules/ROOT/pages/database-internals/transaction-logs.adoc
Labels: cherry-pick-this-to-5.x, dev

#1082 Add temporal and size parameters for `db.tx_log.rotation.retention_policy` (#1077)
  modules/ROOT/pages/database-internals/transaction-logs.adoc
Labels: cherry-picked, 5.x

#1081 added additional step to set NEO4J_PLUGINS env (#1061)
  modules/ROOT/pages/kubernetes/plugins.adoc
Labels: dev, This branch only

#1080 added rhel 9.2 support to list and improved instructions around non-interactive rpm installation
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4

#1086 fix the env NEO4J_DOCKER_IMAGE
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-pick-this-to-5.x

#1087 fix the env NEO4J_DOCKER_IMAGE
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked

#1083 Add parallel runtime information
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.13

#1079 porting content
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/server-syntax.adoc
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-pick-this-to-5.x, dev, clustering, Cypher Manual Restructure

#1085 Update information on `db.transaction.timeout`
  modules/ROOT/pages/database-internals/transaction-management.adoc
Labels: cherry-pick-this-to-5.x, dev

#1084 Make a small adjustment to `:source` command
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, dev

#1091 Update information on `db.transaction.timeout` (#1085)
  modules/ROOT/pages/database-internals/transaction-management.adoc
Labels: cherry-picked, 5.x

#1088 Adding information about JRE
  modules/ROOT/pages/installation/requirements.adoc
Labels: dev, cherry-pick-this-backward

#1092 Adding information about JRE (#1088)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#1093 Make a small adjustment to `:source` command (#1084)
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: 4.4, cherry-picked

#1095 Adding information about JRE (#1088)
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4, cherry-picked

#1096 Adding information about JRE (#1088)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.3

#1097 Adding information about JRE (#1088)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.2

#1098 Adding information about JRE (#1088)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.1

#1094 Make a small adjustment to `:source` command (#1084)
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: cherry-picked, 5.x

#1099 Adding information about JRE (#1088)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.0

#1089 Adding note about OS processor version and OpenSSL
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: dev, cherry-pick-this-backward

#1100 Adding note about OS processor version and OpenSSL (#1089)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1101 Adding note about OS processor version and OpenSSL (#1089)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4, cherry-picked

#1102 Adding note about OS processor version and OpenSSL (#1089)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 4.3

#1107 update the supported plugins
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-pick-this-to-5.x

#1105 4.4 supported plugins
  modules/ROOT/pages/configuration/plugins.adoc
Labels: 4.4

#1106 Adding link to Red Hat official documentation for more info about lif…
  modules/ROOT/pages/installation/requirements.adoc
Labels: dev, cherry-pick-this-backward

#1109 Adding link to Red Hat official documentation for more info about lif…
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#1110 Adding link to Red Hat official documentation for more info about lif…
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4, cherry-picked

#1111 Adding link to Red Hat official documentation for more info about lif…
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.3

#1112 Adding link to Red Hat official documentation for more info about lif…
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.2

#1113 Adding link to Red Hat official documentation for more info about lif…
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.1

#1114 Adding link to Red Hat official documentation for more info about lif…
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 4.0

#1103 Adding note about OS processor version and OpenSSL (#1089)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 4.2

#1118 Remove the wrong windows-service update instruction
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x, dev

#1119 Remove the wrong windows-service update instruction (#1118)
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x

#1108 Moving the command expansion section to a new page
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/kubernetes/operations/maintenance-mode.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: dev, cherry-pick-this-backward

#1120 Moving the command expansion section to a new page (#1108)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/kubernetes/operations/maintenance-mode.adoc
  modules/ROOT/pages/manage-databases/remote-alias.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked, 5.x

#1122 Moving the command expansion section to a new page (#1108)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 4.3

#1125 Moving the command expansion section to a new page #1108
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/command-expansion.adoc
Labels: cherry-picked, 4.0

#1121 4.4 cherry pick 1108
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/kubernetes/operations/maintenance-mode.adoc
  modules/ROOT/pages/manage-databases/remote-alias.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4, cherry-picked

#1128 fixed link and added auto-enable of free servers setting
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/clustering/settings.adoc
Labels: cherry-pick-this-to-5.x, dev, clustering

#1129 fixed link and added auto-enable of free servers setting (#1128)
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/clustering/settings.adoc
Labels: cherry-picked, clustering

#1127 Cordoned servers are preferred first when decreasing allocation count
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/servers.adoc
Labels: dev, clustering

#1130 5.x-cherry-pick-1127
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-picked, 5.x, clustering

#1132 rename ingress.yaml to ingress-values.yaml
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1133 rename ingress.yaml to ingress-values.yaml (#1132)
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-picked, 5.x

#1134 5.x cherry picks 5.13
  antora.yml
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1135 5.x cherry picks for 5.13 part 2
  modules/ROOT/pages/authentication-authorization/access-control.adoc
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1139 Migrate Database Management and Alias management pages from Cypher Ma…
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
  modules/ROOT/pages/composite-databases/administration.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/configuration/password-and-user-recovery.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
  modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/sharding-with-copy.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/database-administration/queries.adoc
  modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/manage-databases/index.adoc
  modules/ROOT/pages/manage-databases/introduction.adoc
  modules/ROOT/pages/routing-decisions.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-picked, 5.x

#1140 Move the access control from the Cypher manual (#1047)
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax_database_privileges.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_hierarchy.svg
  modules/ROOT/images/privileges_hierarchy_database.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
  modules/ROOT/images/privileges_on_graph_syntax.svg
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/authentication-authorization/introduction.adoc
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/manage-execute-permissions.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/authentication-authorization/privileges-immutable.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/authentication-authorization/terminology.adoc
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/setup/routing.adoc
  modules/ROOT/pages/configuration/dynamic-settings.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/monitoring/background-jobs.adoc
  modules/ROOT/pages/monitoring/connection-management.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/monitoring/query-management.adoc
  modules/ROOT/pages/performance/index-configuration.adoc
  modules/ROOT/pages/reference/procedures.adoc
  modules/ROOT/pages/tutorial/access-control.adoc
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
Labels: cherry-picked, 5.x

#1141 5.x cherry pick 5
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax_load_privileges.svg
  modules/ROOT/images/privileges_on_graph_syntax.svg
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-execute-permissions.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/plugins.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1142 porting content (#1079)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/server-syntax.adoc
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-picked, 5.x

#1143 rearranged to accommodate all possible database states (#1045)
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/monitoring/show-databases-monitoring.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: cherry-picked, 5.x

#1144 fix mismatches after resolving merged conflicts
  modules/ROOT/pages/clustering/databases.adoc
Labels: 5.x, This branch only

#1147 fix a broken link after cherry-picking
  modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc
Labels: 5.x, This branch only

#1146 Update information about `:sysinfo` command
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: cherry-picked, dev

#1145 Fix a typo
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
Labels: dev, This branch only

#1149 update description of the procedure db.schema.visualization (#410)
  modules/ROOT/pages/reference/procedures.adoc
  modules/ROOT/partials/procedure-documentation/procedure-reference-community-edition.adoc
  modules/ROOT/partials/procedure-documentation/procedure-reference-complete.adoc
  modules/ROOT/partials/procedure-documentation/procedure-reference-enterprise-edition.adoc
Labels: 4.4, cherry-picked

#1136 Update error message when user database has lost quorum
  modules/ROOT/pages/clustering/disaster-recovery.adoc
Labels: cherry-pick-this-to-5.x, dev

#1150 update the version to 5.14
  antora.yml
Labels: 5.14

#1151 Update error message when user database has lost quorum (#1136)
  modules/ROOT/pages/clustering/disaster-recovery.adoc
Labels: cherry-picked, 5.x

#1152 Remove port 7473 from the services
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/verify-installation.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, 5.13

#1153 Remove port 7473 from the services (#1152)
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/verify-installation.adoc
Labels: cherry-picked, 5.x

#1154 adding support for workload identity in neo4j admin backup (#1131)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#1156 clarify on conf file on cluster members
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, dev, clustering

#1160 clarify on conf file on cluster members (#1156)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1158 remove port 7473
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-outside-k8s.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/verify-cluster-formation.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/verify-rr-joined.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/verify-installation.adoc
Labels: 4.4

#1157 4.4 workload identity
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: 4.4

#1104 Update description of the config `server.cypher.parallel.worker_limit`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1163 Update description of the config `server.cypher.parallel.worker_limit…
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1064 clarify that on Neo4j startup all pagecache warmup activity results in pagefaults
  modules/ROOT/partials/neo4j-metrics/available-metrics.adoc
Labels: 4.4

#1065 Clarify that on Neo4j startup all pagecache warmup activity results in pagefaults
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x
