Repository neo4j/docs-operations, pull requests merged in 2023-08, with the labels that each got.

#944 fixing typo (#943)
  modules/ROOT/pages/kubernetes/plugins.adoc
  preview.yml
Labels: cherry-picked, 5.x

#875 Update Netty version for latest Neo4j version
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-5.x, dev

#946 Update Netty version for latest Neo4j version (#875)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#945 Update cypher-shell.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: dev

#947 update ui-bundle url
  preview.yml
  publish.yml
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, dev

#948 update ui-bundle url (#947)
  preview.yml
Labels: 4.3, cherry-pick-this-to-4.2, cherry-pick-this-to-4.1, cherry-pick-this-to-4.0

#949 Bump exact version to 4.4.24
  antora.yml
Labels: 4.4, This branch only

#951 Update tokens and output
  .github/workflows/docs-deploy-surge.yml
  .github/workflows/docs-pr.yml
  .github/workflows/docs-teardown.yml
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, dev

#929 Improve the description of the metric cluster.raft.message_processing_delay
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x, clustering

#954 Improve the description of the metric cluster.raft.message_processing_delay
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#955 Broken link to File locations page (#953)
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 5.x

#956 Broken link to File locations page (#953)
  modules/ROOT/pages/configuration/plugins.adoc
Labels: 4.4, cherry-picked

#957 Broken link to File locations page (#953)
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 4.3

#958 Broken link to File locations page (#953)
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 4.2

#959 Broken link to File locations page (#953)
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 4.1

#960 Broken link to File locations page (#953)
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 4.0

#950 Adding starting and stopping database state
  modules/ROOT/pages/manage-databases/errors.adoc
Labels: clustering, 5.11

#932 Add info on skipping consistency check in 4.x
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: 4.4, cherry-pick-this-backward

#965 4.1 cherry pick 932
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: cherry-picked, 4.1

#966 Add info on skipping consistency check in 4.x
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: 4.0

#964 Add info on skipping consistency check in 4.x (#932)
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: cherry-picked, 4.2

#906 Instructions to config access token in Azure
  modules/ROOT/images/sso-configuration-tutorials/azure-id.svg
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: dev, cherry-pick-this-backward

#971 Instructions to config access token in Azure (#906)
  modules/ROOT/images/sso-configuration-tutorials/azure-id.svg
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked, 5.x

#972 Instructions to config access token in Azure (#906)
  modules/ROOT/images/sso-configuration-tutorials/azure-id.svg
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: 4.4, cherry-picked

#974 5.11 cherry picks
  modules/ROOT/pages/composite-databases/administration.adoc
  modules/ROOT/pages/manage-databases/errors.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-picked, 5.x

#976 Cherry-pick 5.11
  antora.yml
Labels: cherry-picked, 5.x

#979 Document index metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#980 Add a caption to database state metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#981 Add a caption to database state metrics (#980)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#970 Add vector index procedures
  modules/ROOT/images/cosine_similarity_equation.svg
  modules/ROOT/images/cosine_similarity_equation.tex
  modules/ROOT/images/euclidean_similarity_equation.svg
  modules/ROOT/images/euclidean_similarity_equation.tex
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x, 5.11

#982 Add vector index procedures (#970)
  modules/ROOT/images/cosine_similarity_equation.svg
  modules/ROOT/images/cosine_similarity_equation.tex
  modules/ROOT/images/euclidean_similarity_equation.svg
  modules/ROOT/images/euclidean_similarity_equation.tex
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked

#978 Make links of the removed procedures point to 4.4
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#962 Link hardware requirements to performance
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-pick-this-to-5.x

#983 Make links of the removed procedures point to 4.4 (#978)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#984 Link hardware requirements to performance (#962)
  modules/ROOT/pages/installation/requirements.adoc
Labels: 5.x

#961 Uncomment the link to Docker installation
  modules/ROOT/pages/installation/index.adoc
Labels: cherry-pick-this-to-5.x

#985 Uncomment the link to Docker installation (#961)
  modules/ROOT/pages/installation/index.adoc
Labels: cherry-picked

#986 Remove EE roles and replace with labels on import page
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#988 Fix an error in example for `db.tx_log.rotation.retention_policy`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#990 Fix an error in example for `db.tx_log.rotation.retention_policy` (#988)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked

#989 Remove EE roles and replace with labels on import page (#986)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked

#991 Reword the description to be consistent with the Cypher manual
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#992 Fix broken links
  modules/ROOT/pages/authentication-authorization/access-control.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/composite-databases/queries.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/ports.adoc
  modules/ROOT/pages/database-internals/checkpointing.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/manage-databases/remote-alias.adoc
  modules/ROOT/pages/security/checklist.adoc
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-pick-this-to-5.x

#993 Fix broken links (#992)
  modules/ROOT/pages/authentication-authorization/access-control.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/composite-databases/queries.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/ports.adoc
  modules/ROOT/pages/database-internals/checkpointing.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/manage-databases/remote-alias.adoc
  modules/ROOT/pages/security/checklist.adoc
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-picked, 5.x

#987 Remove usage of "version" or "v" before the version number
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
  modules/ROOT/pages/kubernetes/operations/assign-neo4j-pods.adoc
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
  modules/ROOT/pages/kubernetes/operations/image-pull-secret.adoc
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/monitoring/metrics/enable.adoc
  modules/ROOT/pages/monitoring/metrics/expose.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-configuration.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
  modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#996 Add information on how to configure backup client
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-pick-this-to-5.x

#997 Add information on how to configure backup client (#996)
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-picked

#999 Note the limitations on valid vector dimensions for vector index creation procedure
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x, 5.11

#1004 Bump exact version to 4.4.25
  antora.yml
Labels: 4.4, This branch only

#1003 Update cypher-shell.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: cherry-pick-this-to-5.x, dev

#1002 add a clustering glossary for 4.4
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/glossary.adoc
  modules/ROOT/pages/clustering/index.adoc
Labels: 4.4, clustering, do not cherry-pick

#1009 Display missing elements in the code block
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-pick-this-to-5.x, dev

#1010 Display missing elements in the code block (#1009)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, 5.x

#1011 clarified on seed providers
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, dev, clustering

#1012 clarified on seed providers (#1011)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, clustering

#1008 updated seeding instructions
  modules/ROOT/pages/clustering/seed.adoc
Labels: 4.4, cherry-pick-this-to-4.3, clustering

#1013 resolved conflicts
  modules/ROOT/pages/clustering/seed.adoc
Labels: cherry-picked, 4.3, clustering

#1007 Be explicit that reallocate is optional
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-pick-this-to-5.x, dev, clustering

#1014 manually cherry-pick 1007
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, clustering, 5.11

#1016 added admonition about different values for current and requested counts
  modules/ROOT/pages/clustering/monitoring/show-databases-monitoring.adoc
Labels: cherry-picked, clustering, 5.11
