Repository neo4j/docs-operations, pull requests merged in 2023-12, with the labels that each got.

#1228 Update the description of `<prefix>.cluster.raft.message_processing_timer`
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1225 Add anchors to the metrics tables
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1231 Add anchors to the metrics tables (#1225)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1224 add query for counting databases in a cluster
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: 5.x

#1230 Remove AWS from the MinIO
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: 4.4

#1229 Remove AWS from the MinIO
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x

#1235 Remove AWS from the MinIO (#1229)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#1237 adding clarification to `neo4j-admin backup` command description (#1227)
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-picked, 5.x

#1234 Add new target for `SHOW SUPPORTED PRIVILEGES` (#1215)
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
Labels: cherry-picked

#1233 add query for counting databases in a cluster (#1224)
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: cherry-picked, 5.x

#1240 Update plugins.adoc in Kubernetes
  modules/ROOT/pages/kubernetes/plugins.adoc
Labels: cherry-pick-this forward

#1242 Update plugins.adoc in Kubernetes (#1240)
  modules/ROOT/pages/kubernetes/plugins.adoc
Labels: cherry-picked

#1241 Update cluster related metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x, 5.16

#1238 adding clarification to neo4j-admin backup command description
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: 4.4

#1239 Update the default value of `db.tx_log.rotation.retention_policy`
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
Labels: cherry-pick-this-to-5.x

#1252 Update the default value of `db.tx_log.rotation.retention_policy` (#1239)
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
Labels: cherry-picked, 5.x

#1254 5.x cherry picks release
  antora.yml
  modules/ROOT/images/server-states3.png
  modules/ROOT/pages/clustering/monitoring/show-servers-monitoring.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.15

#1255 Update the version number to 5.16
  antora.yml
Labels: 5.16

#1256 remove connections ad
  publish.yml
Labels: do not cherry-pick

#1246 Add `LOAD ON CIDR` privilege
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax_load_privileges.svg
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
Labels: team-cypher-operations, 5.16

#1259 Removing duplicate content about command expansion
  modules/ROOT/pages/configuration/neo4j-conf.adoc
Labels: cherry-pick-this-backward

#1261 Removing duplicate content about command expansion (#1259)
  modules/ROOT/pages/configuration/neo4j-conf.adoc
Labels: cherry-picked

#1262 Removing duplicate content about command expansion (#1259)
  modules/ROOT/pages/configuration/neo4j-conf.adoc
Labels: cherry-picked

#1263 Removing duplicate content about command expansion (#1259)
  modules/ROOT/pages/configuration/neo4j-conf.adoc
Labels: cherry-picked

#1264 Removing duplicate content about command expansion (#1259)
  modules/ROOT/pages/configuration/neo4j-conf.adoc
Labels: cherry-picked

#1265 Removing duplicate content about command expansion (#1259)
  modules/ROOT/pages/configuration/neo4j-conf.adoc
Labels: cherry-picked

#1267 Update the def.value of `db.tx_log.rotation.retention_policy` (#1257)
  modules/ROOT/pages/database-internals/checkpointing.adoc
Labels: cherry-picked, 5.x

#1266 Remove mention of SINGLE mode
  modules/ROOT/pages/configuration/ports.adoc
Labels: cherry-pick-this-to-5.x

#1269 Remove mention of SINGLE mode (#1266)
  modules/ROOT/pages/configuration/ports.adoc
Labels: cherry-picked, 5.x

#1258 Restructure of the introduction page
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x

#1243 Fix neo4j-admin server validate-config example
  modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
Labels: cherry-pick-this forward

#1274 Restructure of the introduction page (#1258)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked

#1272 Restructure of the introduction page (#1258)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked

#1275 Restructure of the introduction page (#1258)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked

#1276 Restructure of the introduction page (#1258)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked

#1277 Restructure of the introduction page (#1258)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked

#1278 Restructure of the introduction page (#1258)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked

#1279 Improved the store formats section
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
Labels: 4.4

#1273 Fix neo4j-admin server validate-config example (#1243)
  modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
Labels: cherry-picked, dev

#1268 Clarify what routing table shuffling means
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.16

#1253 Update documentation around store formats for block format
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/database-internals/index.adoc
  modules/ROOT/pages/database-internals/locks-deadlocks.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/performance/space-reuse.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
Labels: kernel, 5.16

#1260 Moving the password page to auth
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-pick-this-backward

#1283 Moving the password page to auth (#1260)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-picked

#1284 Moving the password page to auth (#1260)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-picked

#1285 Moving the password page to auth (#1260)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-picked

#1287 Undoing merged changes
  modules/ROOT/pages/configuration/index.adoc
Labels: bug

#1286 Moving the password page to auth (#1260)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-picked

#1288 Undoing merged changes
  modules/ROOT/pages/configuration/index.adoc
Labels: bug

#1289 Moving the password page to auth (#1260)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-picked

#1292 update version to 4.4.29
  antora.yml
Labels: 4.4

#1290 Moving the password page to auth (#1260)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-picked
