Repository neo4j/docs-operations, pull requests merged in 2023-07, with the labels that each got.

#884 offline import marked with CE
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#885 offline import marked with CE
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked, 5.x

#877 improve the description of db.tx_log.rotation.retention_policy
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#886 Improve the description of db.tx_log.rotation.retention_policy
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#887 add label to configs introduced in 5.7
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#888 add label to configs introduced in 5.7 (#887)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#874 Add examples for performing differential backup and restore
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#889 Add examples for performing differential backup and restore (#874)
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, 5.x

#890 revert `file:/tmp/backup1.backup`
  modules/ROOT/pages/clustering/databases.adoc
Labels: dev, This branch only, do not cherry-pick

#837 Automatically enable free servers
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.10

#876 Improvements to the neo4j-admin copy documentation
  modules/ROOT/pages/backup-restore/copy-database.adoc
Labels: 4.4

#892 Add a section about restoring a backup in a cluster
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#893 add a section about restoring a backup in a cluster
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, 5.x

#894 Bump exact version to 4.4.23
  antora.yml
Labels: 4.4, This branch only

#896 added debian 12 to the list of supported operating systems
  modules/ROOT/pages/installation/requirements.adoc
Labels: 5.x

#897 updated supported operating systems doc to include more recent operating systems
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4

#898 added debian 12 to the list of supported operating systems (#896)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#895 Fix typo in max_databases docker config
  modules/ROOT/pages/docker/ref-settings.adoc
Labels: cherry-pick-this forward, 5.x

#899 Fix typo in max_databases docker config
  modules/ROOT/pages/docker/ref-settings.adoc
Labels: cherry-picked

#891 Document how to move from single to cluster
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
Labels: dev

#901 [online backup] database parameter table headers fix
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-pick-this-to-5.x

#909 fixed table headers for db parameter in online backup docs
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-picked, 5.x

#904 fix retrieving serverId command for seed cluster section
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-pick-this-to-5.x

#910 fix retrieving serverId command for seed cluster section (#904)
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked

#907 Removing obsolete encryption arguments
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: dev, cherry-pick-this-backward

#912 Removing obsolete encryption arguments (#907)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#914 Automatically enable free servers #837
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#915 Update Neo4j version (#840)
  antora.yml
Labels: cherry-picked

#916 Document the few new metrics and add the Dynamic label to two configs…
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#900 Add new column `composite` to `SHOW ALIASES`
  modules/ROOT/pages/composite-databases/administration.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: team-cypher-operations, 5.11

#903 Fix systemctl enable neo4j.service documentation
  modules/ROOT/pages/installation/linux/tarball.adoc
Labels: cherry-pick-this forward, 5.x

#918 Fix systemctl enable neo4j.service documentation (#903)
  modules/ROOT/pages/installation/linux/tarball.adoc
Labels: cherry-picked

#917 Adding information about port 7688
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: dev, cherry-pick-this-backward

#920 Adding information about port 7688 (#917)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#921 Adding information about port 7688 (#917)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4, cherry-picked

#922 Adding information about port 7688 #917
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 4.3

#923 Adding information about port 7688 #917
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 4.2

#919 Add support for PVC labels
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
Labels: cherry-pick-this-to-5.x, 5.10

#925 Remove the table with supported plugins from docker and link to the p…
  modules/ROOT/pages/docker/operations.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#927 remove the table with supported plugins from docker and link to the plugins page
  modules/ROOT/pages/docker/operations.adoc
Labels: cherry-picked

#926 update the dynamic settings
  modules/ROOT/pages/configuration/dynamic-settings.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#928 update the dynamic settings (#926)
  modules/ROOT/pages/configuration/dynamic-settings.adoc
Labels: cherry-picked

#911 Improve the logging page
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-5.x, 5.x, kernel

#931 Improve the logging page (#911)
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, 5.x

#934 Add support for backing up multiple dbs with neo4j-admin helm
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: 4.4

#924 Add support for PVC labels (#919)
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
Labels: cherry-picked, DO NOT MERGE, 5.x

#933 Add support for backing up multiple dbs with neo4j-admin helm
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x, 5.10

#936 Add support for backing up multiple dbs with neo4j-admin helm (#933)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#937 Add support for adding nodeSelector labels with neo4j-admin helm
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x

#938 Add support for adding nodeSelector labels with neo4j-admin helm (#937)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#939 Update the helm charts and add the nodeSelector for neo4j-admin
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
  modules/ROOT/pages/kubernetes/operations/assign-neo4j-pods.adoc
Labels: cherry-pick-this-to-5.x

#935 Add support for adding nodeSelector labels with neo4j-admin helm
  modules/ROOT/pages/kubernetes/operations/assign-neo4j-pods.adoc
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: 4.4

#940 Update the helm charts and add the nodeSelector for neo4j-admin (#939)
  modules/ROOT/pages/kubernetes/helm-charts-setup.adoc
  modules/ROOT/pages/kubernetes/operations/assign-neo4j-pods.adoc
Labels: cherry-picked, 5.x
