Repository neo4j/docs-operations, pull requests merged in 2024-11, with the labels that each got.

#1925 Deprecate `seedConfig`, and `seedCredentials`
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: dev, team-cypher-operations, clustering, 5.26

#1923 Update config settings
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.26

#1932 add missing immutable keyword to server management examples
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
Labels: dev, team-cypher-operations, 5.x

#1940 Add supported file systems to the requirements page
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1941 Add supported file systems to the requirements page (#1940)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#1939 Fix rpm installation
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: 4.4

#1942 Add supported file systems to the requirements page (#1940)
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4, cherry-picked

#1936 Products folder in CE vs EE
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: cherry-pick-this-to-5.x

#1943 Products folder in CE vs EE (#1936)
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: cherry-picked, 5.x

#1938 Remove deprecation for seedConfig
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: team-cypher-operations, clustering, 5.26

#1935 Document `--multiline-fields-format` option
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 5.26

#1933 Update `server.metrics.filter`, add new 5.26 configuration settings
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.26

#1937 replacing an existing database is only for EE
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: cherry-pick-this-to-5.x

#1944 replacing an existing database is only for EE (#1937)
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: cherry-picked, 5.x

#1947 Add a warning about removing disc.service v1
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: cherry-pick-this-to-5.x

#1949 Add a warning about removing disc.service v1 (#1947)
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: cherry-picked, 5.x

#1946 Clarify neo4j-admin server report --database option
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1950 Clarify neo4j-admin server report --database option (#1946)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
Labels: cherry-picked, 5.x

#1951 Clarify neo4j-admin server report --database option (#1946)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
Labels: 4.4, cherry-picked

#1924 Add an MVCC related metric
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 5.26

#1955 Remove the backticks around * and ? to fix the failing test
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
Labels: cherry-pick-this-to-5.x

#1945 Add more info about -additional-config
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/inspect.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-memrec.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-5.x

#1957 Add more info about -additional-config (#1945)
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/inspect.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-memrec.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-picked, 5.x

#1956 Remove the backticks around * and ? to fix the failing test (#1955)
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
Labels: cherry-picked

#1958 Update Table 1. Community Edition vs Enterprise Edition key features
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x

#1959 Using quoting instead of escaping with backticks
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations

#1963 Using quoting instead of escaping with backticks (#1959)
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
Labels: cherry-picked, 5.x

#1964 Update the configurations
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1966 Update the configurations (#1964)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1858 Add neo4j-admin-import section and parameter details for Parquet.
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 5.26

#1968 Add refinement to the note of deprecated ciphers
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 5.26

#1970 Remove the note and redesign the structure of the Monitor replication status page
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
Labels: cherry-pick-this-to-5.x, clustering

#1972 Remove the note and redesign the structure of the Monitor replication status page (#1970)
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
Labels: cherry-picked, 5.x

#1969 Add deprecation labels to configs
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.26

#1971 Fix the anchor
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1967 fix load command example
  modules/ROOT/pages/kubernetes/operations/dump-load.adoc
Labels: 5.x, cherry-pick-this-backward

#1974 fix load command example (#1967)
  modules/ROOT/pages/kubernetes/operations/dump-load.adoc
Labels: cherry-picked, dev

#1979 Add a line about the dynamic version of netty-tcnative located under …
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1820 Restructure Procedures page and add new Details tables
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/database-administration/routing-decisions.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/performance/index-configuration.adoc
  modules/ROOT/pages/performance/space-reuse.adoc
  modules/ROOT/pages/performance/statistics-execution-plans.adoc
  modules/ROOT/pages/procedures.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: DO NOT MERGE, kernel, 5.26

#1982 Bump the version number to 4.4.39
  antora.yml
Labels: 4.4

#1986 Fix the deprecation label for `dbms.cluster.discovery.type`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.x, cherry-pick-this-backward

#1980 add note about database name in query log
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-composite

#1987 Fix the deprecation label for `dbms.cluster.discovery.type` (#1986)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked

#1989 Add seed from URI differential backup support
  modules/ROOT/pages/clustering/databases.adoc
Labels: dev, 5.26

#1992 Update the note about the default GQLSTATUS code 50N42
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-5.x

#1993 Update the note about the default GQLSTATUS code 50N42 (#1992)
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, 5.x

#1995 Fixes to Procedure tables
  modules/ROOT/pages/procedures.adoc
Labels: 5.26

#1998 Update the debug.log descriptions to emphasize that change of format must not be changed (#1997)
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, 5.x
