Repository neo4j/docs-operations, pull requests merged in 2024-03, with the labels that each got.

#1443 Add a note in restore a database backup to consider CDC implications
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: dev, team-cypher-operations

#1460 Reorganize the upgrade on k8s page and change the title
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/operations/index.adoc
  modules/ROOT/pages/kubernetes/operations/upgrade.adoc
Labels: cherry-pick-this-to-5.x

#1468 Reorganize the upgrade on k8s page and change the title (#1460)
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/operations/index.adoc
  modules/ROOT/pages/kubernetes/operations/upgrade.adoc
Labels: cherry-picked, 5.x

#1459 update the reverse-proxy yaml to support privilege and access control settings for a Container
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-pick-this-to-5.x, 5.17

#1453 Add section on limitations around privileges and missing labels
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
Labels: dev, team-cypher-operations, cherry-pick-this-backward

#1469 update the reverse-proxy yaml to support privilege and access control settings for a Container (#1459)
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-picked, 5.x

#1470 Add section on limitations around privileges and missing labels (#1453)
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
Labels: cherry-picked, 5.x

#1467 Update the link to the Transaction management section
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
Labels: cherry-pick-this-to-5.x

#1471 Update the link to the Transaction management section (#1467)
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
Labels: cherry-picked, 5.x

#1438 Update plugins.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
Labels: cherry-pick-this forward

#1473 Replace labels with roles
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/set-initial-password.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-internals/checkpointing.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/database-internals/transaction-management.adoc
  modules/ROOT/pages/docker/introduction.adoc
  modules/ROOT/pages/kubernetes/authentication-authorization.adoc
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/reference/procedures.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
Labels: cherry-pick-this-to-5.x

#1476 Replace labels with roles (#1473)
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/set-initial-password.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-internals/checkpointing.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/database-internals/transaction-management.adoc
  modules/ROOT/pages/docker/introduction.adoc
  modules/ROOT/pages/kubernetes/authentication-authorization.adoc
  modules/ROOT/pages/kubernetes/persistent-volumes.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/reference/procedures.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/validate-config.adoc
Labels: cherry-picked, 5.x

#1479 Fix added version number
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.18

#1474 Add bolt configs
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.18

#1478 Document db.create.setRelationshipVectorProperty procedure
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.18

#1484 Update the dev version to 5.19
  antora.yml
Labels: 5.19

#1475 Improve Changing the store format
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-pick-this-to-5.x

#1485 Improve Changing the store format (#1475)
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-picked, 5.x

#1486 Add Store Format link to `--format` parameter entry
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, dev, kernel

#1487 Cherrypick into 5.x: Add Store Format link to `--format` parameter entry
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x, kernel

#1477 Add a note about using additional-config with the import command
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#1492 Add a note about using additional-config with the import command (#1477)
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#1493 Add a note about LIST<INTEGER | FLOAT> (#1491)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1494 Fix dbms.jvm.additionalto be server.jvm.additional
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-pick-this-to-5.x

#1495 Fix dbms.jvm.additionalto be server.jvm.additional (#1494)
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#1497 Add page-aliases attr on the neo4j admin report page
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
Labels: 4.3

#1490 Remove azp checking from docs in line with OIDC spec update
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: dev, team-cypher-operations

#1488 Add a step for reseeding the cluster after migration
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-pick-this-to-5.x, clustering

#1432 Editorial review of the descriptions of the restore options
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-pick-this-to-5.x, clustering

#1499 Add information for using JNA
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-pick-this-to-5.x

#1503 Add information for using JNA (#1499)
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#1501 clarifying that DBMS privileges do not get backed up
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, team-cypher-operations

#1504 S3 URI support for admin database import and database load/dump
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 5.19

#1496 Fix the Deprecated label of the cdc related procedures by adding v.n.…
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1511 Fix the Deprecated label of the cdc related procedures by adding v.n.5.17 (#1496)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked

#1500 make all mentions of NEO4J_HOME and /bin the same
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/backup-restore/modes.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/setup/encryption.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/plugins.adoc
  modules/ROOT/pages/configuration/set-initial-password.adoc
  modules/ROOT/pages/database-administration/composite-databases/sharding-with-copy.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/performance/space-reuse.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-5.x

#1513 make all mentions of NEO4J_HOME and /bin the same (#1500)
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/backup-restore/modes.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/setup/encryption.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/plugins.adoc
  modules/ROOT/pages/configuration/set-initial-password.adoc
  modules/ROOT/pages/database-administration/composite-databases/sharding-with-copy.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/performance/space-reuse.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-picked, 5.x

#1512 A few more neo4j-admin paths
  modules/ROOT/pages/backup-restore/modes.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-configuration.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#1515 5.x neo4j paths
  modules/ROOT/pages/backup-restore/modes.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-configuration.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#1516 Update the description of dbms.track_query_cpu_time
  modules/ROOT/partials/neo4j-config/all-settings.adoc
Labels: 4.3, cherry-pick-this-to-4.2, cherry-pick-this-to-4.1, cherry-pick-this-to-4.0

#1517 Update the description of dbms.track_query_cpu_time (#1516)
  modules/ROOT/partials/neo4j-config/all-settings.adoc
Labels: cherry-picked, 4.0

#1518 Update the description of dbms.track_query_cpu_time (#1516)
  modules/ROOT/partials/neo4j-config/all-settings.adoc
Labels: cherry-picked, 4.1

#1519 Update the description of dbms.track_query_cpu_time (#1516)
  modules/ROOT/partials/neo4j-config/all-settings.adoc
Labels: cherry-picked, 4.2

#1498 Improve the dump page and add default location for the dumps
  modules/ROOT/pages/backup-restore/offline-backup.adoc
Labels: cherry-pick-this-to-5.x

#1520 Improve the dump page and add default location for the dumps (#1498)
  modules/ROOT/pages/backup-restore/offline-backup.adoc
Labels: cherry-picked, 5.x

#1521 Add page-aliases to the clustering section (#1509)
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/clustering/setup/encryption.adoc
  modules/ROOT/pages/clustering/setup/routing.adoc
Labels: cherry-picked, 5.x

#1514 Improve the Removed procedures section
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1522 Improve the Removed procedures section (#1514)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1523 Change "Starting the service automatically on system start" section and add code
  modules/ROOT/pages/installation/linux/debian.adoc
Labels: cherry-pick-this-to-5.x

#1524 5.x fi new debian command
  modules/ROOT/pages/installation/linux/debian.adoc
Labels: cherry-picked, 5.x

#1525 Update the exact version to 4.4.32
  antora.yml
Labels: 4.4
