Repository neo4j/docs-operations, pull requests merged in 2024-06, with the labels that each got.

#1615 Add `WAIT` examples to START/STOP sections and syntax tables to the Cypher adm commands
  modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/wait-options.adoc
Labels: cherry-pick-this-to-5.x

#1654 Add `WAIT` examples to START/STOP sections and syntax tables to the Cypher adm commands (#1615)
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/wait-options.adoc
  modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
Labels: cherry-picked, 5.x

#1617 Improve the cluster config descriptions
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: DO NOT MERGE, 5.21

#1638 improve the description of import format option
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
Labels: 5.21

#1655 Prepare the connection setting descriptions for testing
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
Labels: 5.21

#1620 Describe setting to infer labels.
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: team-cypher-planner, 5.21

#1658 Explain how neo4j metric names are transformed in Prometheus
  modules/ROOT/pages/monitoring/metrics/expose.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1661 Explain how neo4j metric names are transformed in Prometheus (#1658)
  modules/ROOT/pages/monitoring/metrics/expose.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1662 Fix the wrong Cypher commands for showing a specific index and a few typos
  modules/ROOT/pages/performance/index-configuration.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1668 Fix the wrong Cypher commands for showing a specific index and a few typos (#1662)
  modules/ROOT/pages/performance/index-configuration.adoc
Labels: cherry-picked, 5.x

#1666 Editorial update of the cypher shell help to prepare for docs testing
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: 5.21

#1665 Rename the underscore in https://neo4j.com/docs/usage_data/ with a hyphen
  modules/ROOT/pages/installation/index.adoc
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x

#1664 Aura instance must be accessible from the machine running `neo4j-admin`
  modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
Labels: 4.4

#1660 Add a new Bolt metric `<prefix>.dbms.bolt.worker_thread_bound_time`
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 5.21

#1663 Aura instance must be accessible from the machine running `neo4j-admin`
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-5.x

#1671 Aura instance must be accessible from the machine running `neo4j-admin`
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-picked, 5.x

#1076 Property rules documentation
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/images/privileges_on_graph_syntax.svg
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
Labels: team-cypher-operations, 5.21

#1673 Fix displaying of the default value of the config `metrics.filter`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1670 Rename the underscore in https://neo4j.com/docs/usage_data/ with a hyphen
  modules/ROOT/pages/installation/index.adoc
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#1675 Fix displaying of the default value of the config `metrics.filter` (#1673)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1652 Add the metric `<prefix.>store.size.available_reserved`
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 5.21

#1672 Add new configs for full-text indexes
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.21

#1676 Clarity the token/NAME MANAGEMENT privilege (#1674)
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
Labels: cherry-picked, 5.x

#1677 Replace comma with period
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-pick-this-to-5.x

#1678 Fix the formatting in Restore a full backup section
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-pick-this-to-5.x

#1680 Replace comma with period (#1677)
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, 5.x

#1681 Fix the formatting in Restore a full backup section (#1678)
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, 5.x

#1679 Add a note that the users do not need to compact the store prior to running neo4j-admin database migrate
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-pick-this-to-5.x

#1685 Add a note that the users do not need to compact the store prior to running neo4j-admin database migrate (#1679)
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-picked, 5.x

#1686 first label (#1683)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked

#1688 Add a tip about needing server and client usage in intra-cluster TLS certificates
  modules/ROOT/pages/clustering/setup/encryption.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1690 Add a tip about needing server and client usage in intra-cluster TLS …
  modules/ROOT/pages/clustering/setup/encryption.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1691 Add a tip about needing server and client usage in intra-cluster TLS certificates
  modules/ROOT/pages/clustering/intra-cluster-encryption.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4, copied

#1684 Remove mismatches from the `genai.vector.encodeBatch` signature
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.22

#1695 Enable server config should be true
  modules/ROOT/pages/kubernetes/operations/scaling.adoc
Labels: cherry-pick-this-to-5.x

#1696 Enable server config should be true (#1695)
  modules/ROOT/pages/kubernetes/operations/scaling.adoc
Labels: cherry-picked, 5.x

#1669 Fix the wrong Cypher commands for showing a specific index and editorial updates of the page
  modules/ROOT/pages/performance/index-configuration.adoc
Labels: 4.4, cherry-pick-this-to-4.3

#1698 Fix the wrong Cypher commands for showing a specific index and editorial updates of the page (#1669)
  modules/ROOT/pages/performance/index-configuration.adoc
Labels: cherry-picked, 4.3

#1701 5.20 cherry picks
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/images/privileges_on_graph_syntax.svg
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked, 5.x

#1702 5.20 cherry picks2
  .gitignore
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1703 5.20 cherry picks3
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/partials/gcs-credentials.adoc
Labels: cherry-picked, 5.x

#1704 Update the version to 5.22
  antora.yml
Labels: 5.22

#1700 Add an example of `neo4j-admin database upload` for Windows users
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-5.x

#1693 Added lighthouse public settings
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: clustering, 5.22

#1705 Add an example of `neo4j-admin database upload` for Windows users (#1700)
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-picked, 5.x

#1692 Add new lighthouse metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: clustering, 5.22
