Repository neo4j/docs-operations, pull requests merged in 2024-05, with the labels that each got.

#1593 Update instructions on how to set up a dynamic encrypted password
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, cherry-pick-this-to-4.3, cherry-pick-this-to-4.2

#1595 Update instructions on how to set up a dynamic encrypted password (#1593)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1596 Update instructions on how to set up a dynamic encrypted password (#1…
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4, cherry-picked

#1597 Update instructions on how to set up a dynamic encrypted password (#1593)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 4.3

#1598 Update instructions on how to set up a dynamic encrypted password (#1593)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 4.2

#1592 Add new configs `dbms.security.http_static_content_security_policy_header`, `server.http.transaction_idle_timeout`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.20

#1574 Add more details for COSI for AWS
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/partials/aws-s3-credentials.adoc
  modules/ROOT/partials/aws-s3-overrides.adoc
Labels: 5.20

#1604 Document enabling a server using neo4j.operations
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/operations/scaling.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
Labels: 5.20

#1599 Update incremental import note as it supports the block format
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 5.20

#1590 Fix the mistake about Neo4j Helm chart and service accounts
  modules/ROOT/pages/kubernetes/authentication-authorization.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1607 Fix the mistake about Neo4j Helm chart and service accounts (#1590)
  modules/ROOT/pages/kubernetes/authentication-authorization.adoc
Labels: cherry-picked, 5.x

#1608 Updating link to CDC after structural changes in the docset (#1600)
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked

#1609 Fix the error about the Neo4j Helm chart and service account
  modules/ROOT/pages/kubernetes/configuration.adoc
Labels: 4.4, copied

#1602 Build release update (#1587)
  .github/workflows/scorecard.yml
  .gitignore
  package-lock.json
  publish.yml
Labels: cherry-picked, 5.x

#1603 add a link to anonymous usage data report
  modules/ROOT/pages/installation/index.adoc
  modules/ROOT/pages/introduction.adoc
Labels: 5.20

#1577 Document the storeFormat option for create database
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, kernel

#1610 Document the storeFormat option for create database (#1577)
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-picked, 5.x

#1606 Add some possible options for neo4j-admin server license
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
Labels: cherry-pick-this-to-5.x

#1611 Add some possible options for neo4j-admin server license (#1606)
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
Labels: cherry-picked, 5.x

#1605 Add eval option to neo4j.acceptLicenseAgreement
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/prerequisites.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/create-value-file.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/prerequisites.adoc
Labels: cherry-pick-this-to-5.x

#1612 Add eval option to neo4j.acceptLicenseAgreement (#1605)
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/prerequisites.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/create-value-file.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/prerequisites.adoc
Labels: cherry-picked, 5.x

#1594 Update the `load` command description as it supports full backups
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: 5.20

#1578 Add the --copy-schema option
  modules/ROOT/pages/backup-restore/copy-database.adoc
Labels: kernel, 5.20

#1601 Document anomalies under read-committed.
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
  modules/ROOT/pages/database-internals/index.adoc
  modules/ROOT/pages/database-internals/transaction-management.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, team-cypher-planner

#1613 Document anomalies under read-committed. (#1601)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
  modules/ROOT/pages/database-internals/index.adoc
  modules/ROOT/pages/database-internals/transaction-management.adoc
Labels: cherry-picked, 5.x

#1614 Update v.n. to 4.4.34
  antora.yml
Labels: 4.4

#1616 Add 5.20 label to the config `dbms.usage_report.enabled`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.20

#1591 Clarify the `neo4j-admin.conf` file permissions for using `--expand-c…
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: cherry-pick-this-to-5.x

#1618 Add option to set access mode in cypher shell
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: 5.20

#1621 Clarify the `neo4j-admin.conf` file permissions for using `--expand-c…
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: cherry-picked, 5.x

#1623 Add comment on `DEALLOCATED` being state eventual (#1622)
  modules/ROOT/images/server-states4.png
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-picked, 5.x

#1586 Restructure the section on how to administer composite db
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/create-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/delete-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/list-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/routing-decisions.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-pick-this-to-5.x

#1624 Clarify that only physical dbs can be backed up
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-pick-this-to-5.x

#1625 Restructure the section on how to administer composite db (#1586)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/create-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/delete-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/list-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/routing-decisions.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-picked, 5.x

#1627 Remove the note that Neo4j supports SELinux by default
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-pick-this-backward

#1629 Remove the note that Neo4j supports SELinux by default
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: 4.4, cherry-picked, 3.5, cherry-pick-this-to-4.3, cherry-pick-this-to-4.2, cherry-pick-this-to-4.1, cherry-pick-this-to-4.0

#1630 Remove the note that Neo4j supports SELinux by default (#1629)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, 4.3

#1631 Remove the note that Neo4j supports SELinux by default (#1629)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, 4.2

#1632 Remove the note that Neo4j supports SELinux by default (#1629)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, 4.1

#1633 Remove the note that Neo4j supports SELinux by default (#1629)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, 4.0

#1628 Remove the note that Neo4j supports SELinux by default (#1627)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, 5.x

#1634 Fix a typo that says backup can compact data store
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: cherry-pick-this-to-5.x

#1635 Fix a typo that says backup can compact data store (#1634)
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: cherry-picked, 5.x

#1641 Cherry-picks for 5.20 release. Part 2
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/installation/index.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/operations/scaling.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/partials/aws-s3-credentials.adoc
  modules/ROOT/partials/aws-s3-overrides.adoc
Labels: 5.x

#1642 Add the --copy-schema option (#1578)
  modules/ROOT/pages/backup-restore/copy-database.adoc
Labels: cherry-picked, 5.x

#1626 Clarify that only physical dbs can be backed up (#1624)
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-picked, 5.x

#1643 Update dev to 5.21
  antora.yml
Labels: 5.21

#1645 Add label Enterprise to the products and metrics folders
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: cherry-pick-this-to-5.x

#1639 Add openJDK to MacOS and a note that we also support Java 21
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/requirements.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x

#1646 Add label Enterprise to the products and metrics folders (#1645)
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: cherry-picked, 5.x

#1647 Add openJDK to MacOS and a note that we also support Java 21 (#1639)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/requirements.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x

#1648 Fix asciidoc syntax in `dbms.usage_report.enabled`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.x, cherry-pick-this-backward

#1649 Fix metric prefix
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 5.x, cherry-pick-this-backward

#1650 Fix asciidoc syntax in `dbms.usage_report.enabled` (#1648)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked

#1651 Fix prefix
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked

#1636 Clarify a few details around Neo4j plugins
  modules/ROOT/pages/configuration/index.adoc
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-pick-this-to-5.x

#1653 Clarify a few details around Neo4j plugins (#1636)
  modules/ROOT/pages/configuration/index.adoc
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked, 5.x
