Repository neo4j/docs-operations, pull requests merged in 2024-04, with the labels that each got.

#1507 Add an example to the online backup with lists of database names
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-pick-this-to-5.x, clustering

#1527 Add an example to the online backup with lists of database names (#1507)
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-picked, 5.x

#1526 Update the steps for changing the store format in a cluster
  modules/ROOT/pages/database-internals/store-formats.adoc
  package-lock.json
Labels: cherry-pick-this-to-5.x

#1530 Update the steps for changing the store format in a cluster (#1526)
  modules/ROOT/pages/database-internals/store-formats.adoc
  package-lock.json
Labels: cherry-picked, 5.x

#1528 Order the procedure labels
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1531 Order the procedure labels (#1528)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1533 Fix asciidoc syntax mistake to reflect the Deprecated label for `server.max_databases`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1534 Fix asciidoc syntax mistake to reflect the Deprecated label for `server.max_databases` (#1533)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1537 Title was missing a word
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations

#1536 Add missing genai.vector.listEncodingProviders
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.19

#1538 Title was missing a word (#1537)
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
Labels: cherry-picked, 5.x

#1529 Update monitoring.adoc: fixed typo
  modules/ROOT/pages/kubernetes/monitoring.adoc
Labels: cherry-pick-this forward

#1541 Fix a typo
  modules/ROOT/pages/kubernetes/monitoring.adoc
Labels: This branch only

#1540 Add license keys for Bloom and GDS to Additional files to back up
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: cherry-pick-this-to-5.x

#1539 Fix config mismatches
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1543 Fix config mismatches (#1539)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1546 Update the steps for installing Neo4j via a package installer
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-pick-this-to-5.x

#1548 Update the steps for installing Neo4j via a package installer (#1546)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, 5.x

#1550 Update the dev version to 5.20
  antora.yml
Labels: 5.20

#1551 Update accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-pick-this forward

#1553 Fix `page-aliases` attr in the file Create, start and stop db
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: cherry-pick-this-to-5.x

#1552 Update accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-pick-this forward

#1555 Update accessing-neo4j-ingress.adoc (#1552)
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-picked

#1554 Update accessing-neo4j-ingress.adoc (#1551)
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-picked

#1547 A short editorial review of disaster recovery page, update the misleading steps, and update the error message
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  package-lock.json
Labels: cherry-pick-this-to-5.x

#1556 Restructure the Managing standard databases page (#1532)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  modules/ROOT/pages/clustering/monitoring/show-databases-monitoring.adoc
  modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/wait-options.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-picked, 5.x

#1558 Fix `page-aliases` attr in the file Create, start and stop db (#1553)
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: cherry-picked, 5.x

#1559 Add missing metric <prefix>.transaction.validation_failure (#1544)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1535 Fix mismatches in the backup and restore section
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: 5.20

#1062 Improve the checkpoint setting descriptions
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.20

#1561 Fix the mismatches on the backup and restore section
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: 5.20

#1563 Fix a broken link to the CDC docs
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  package-lock.json
Labels: cherry-pick-this-to-5.x

#1564 Fix a broken link to the CDC docs (#1563)
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  package-lock.json
Labels: cherry-picked, 5.x

#1565 fixed link
  modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
  package-lock.json
Labels: 4.4

#1562 Document SHOW DATABASES fields that can be NULL
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Labels: team-cypher-operations, 5.20

#1567 Change `IF EXISTS` to `IF NOT EXISTS`
  modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: cherry-pick-this-to-5.x

#1570 Change `IF EXISTS` to `IF NOT EXISTS` (#1567)
  modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: cherry-picked, 5.x

#1560 Add dbms.usage_report.enabled config
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.20

#1571 Use unicode on CSV file delimiters example
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, dev, kernel

#1573 Use unicode on CSV file delimiters example
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x, kernel

#1575 Don't use `0x` prefix to reference the unicode code point
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, dev, kernel

#1576 Don't use `0x` prefix to reference the unicode code point
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x, kernel

#1572 Attempt to provide definition and usage example for `raftIndexLagThreshold`
  modules/ROOT/pages/clustering/monitoring/endpoints.adoc
Labels: cherry-pick-this-to-5.x

#1579 Attempt to provide definition and usage example for `raftIndexLagThreshold` (#1572)
  modules/ROOT/pages/clustering/monitoring/endpoints.adoc
Labels: cherry-picked, 5.x

#1580 Add definition for `raftIndexLagThreshold`
  modules/ROOT/pages/monitoring/causal-cluster/http-endpoints.adoc
Labels: 4.4, cherry-picked

#1582 Update the exact version to 4.4.33
  antora.yml
Labels: 4.4

#1581 Update Netty and tcnative versions
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4, do not cherry-pick

#1583 Update info about Netty versions
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.3, do not cherry-pick

#1584 Remove v4.4 from the table on Netty for 5.x series
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-5.x

#1585 Remove v4.4 from the table on Netty for 5.x series (#1584)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1588 Update links to the deployment-center and replace `#` with `?`
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
  preview.yml
  publish.yml
Labels: cherry-pick-this-to-5.x

#1589 Update links to the deployment-center and replace `#` with `?` (#1588)
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
  preview.yml
  publish.yml
Labels: cherry-picked, 5.x
