Repository neo4j/docs-operations, pull requests merged in 2024-02, with the labels that each got.

#1386 update the descrption of dbms.cluster.discovery.resolver_type
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1393 change label not on aura for manage aliases for composite dbs
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
Labels: bug, cherry-pick-this-to-5.x, 5.x

#1384 Fixing page-aliases with more options to previous existing links
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/sharding-with-copy.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-pick-this-to-5.x

#1330 Restructure the table of file def locations
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: WIP

#1395 Fixing page-aliases with more options to previous existing links (#1384)
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/database-administration/composite-databases/manage-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/sharding-with-copy.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-administration/standard-databases/manage-databases.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-picked, 5.x

#1392 update the description of dbms.cluster.discovery.resolver_type (#1386)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1361 Bring metric class names in line with those in the code
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1396 Remaining page aliases
  modules/ROOT/pages/clustering/clustering-advanced/index.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
Labels: cherry-pick-this-to-5.x

#1399 Bring metric class names in line with those in the code (#1361)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1397 Restructure the table of file def locations (#1330)
  modules/ROOT/pages/configuration/file-locations.adoc
Labels: cherry-picked, 5.x

#1381 Label db state metrics with 5.7
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1385 Fix names of the Bolt driver metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1400 Label db state metrics with 5.7 (#1381)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1401 Fix names of the Bolt driver metrics (#1385)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1402 Add vector indexes to the available features table
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x

#1404 Add vector indexes to the available features table (#1402)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked, 5.x

#1403 updated mentions of ubi8 docker images to ubi9
  modules/ROOT/pages/docker/introduction.adoc
Labels: 5.17

#1406 Fix the Bolt metrics names by adding `dbms`
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1408 Fix the Bolt metrics names by adding `dbms` (#1406)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1383 Update cypher-shell.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: 5.17

#1407 Fix the link to the Composite databases in v5
  modules/ROOT/pages/fabric/introduction.adoc
Labels: 4.4

#1410 Remove beta label from Block format
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x

#1411 Remove beta label from Block format (#1410)
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked, 5.x

#1413 Update the Windows installation steps
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x

#1414 Update the Windows installation steps (#1413)
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x

#1412 Add genai.vector.encodeBatch to the list of procedures
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1415 Add genai.vector.encodeBatch to the list of procedures (#1412)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#1417 Helm Chart installs Community Edition by default
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
Labels: cherry-pick-this-to-5.x

#1419 Helm Chart installs Community Edition by default (#1417)
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/create-value-file.adoc
Labels: cherry-picked, 5.x

#1418 Add support for backing up a database to on-prem storage
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x, 5.16

#1420 Add support for backing up a database to on-prem storage (#1418)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#1422 Fix missing quote in admin-import property types section
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#1424 Fix missing quote in admin-import property types section (#1422)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, dev

#1423 add deprecated causal clustering metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: clustering

#1425 add deprecated causal clustering metrics (#1423)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x, clustering

#1428 Add CDC to the feature table
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x

#1430 Add CDC to the feature table (#1428)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked, 5.x

#1409 Improve descriptions of the query routing metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1431 Improve descriptions of the query routing metrics (#1409)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1434 Update the store format page (#1421)
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#1435 Add third-level titles to the Metrics ref page
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1436 Cherry-picks for 5.17
  antora.yml
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/dynamic-settings.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/plugins.adoc
  modules/ROOT/pages/docker/introduction.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/reference/procedures.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
Labels: cherry-picked, 5.x

#1437 update the version to 5.18
  antora.yml
Labels: 5.18

#1439 Add third-level titles to the Metrics ref page (#1435)
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1442 Add support for providing args in a file (#1441)
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#1446 Add config `server.http_enabled_transports` related to HTTP/2 support
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1445 Fix dbms.memory.transaction.total.max description
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, dev, kernel

#1447 Update configuration-settings.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1440 Adding clarification that sub-admin roles should not be able to change their own privileges
  modules/ROOT/pages/tutorial/access-control.adoc
Labels: team-cypher-operations, cherry-pick-this-backward, 5.18

#1449 Fix default value of `server.http_enabled_transports`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1427 neo4j-admin report doc update for added option
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
Labels: 4.4, kernel

#1451 Adding clarification that sub-admin roles should not be able to change their own privileges
  modules/ROOT/pages/authentication-authorization/access-control.adoc
Labels: 4.4, cherry-picked

#1455 fixed link
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
Labels: cherry-pick-this-to-5.x

#1454 remove the note about dropping the database
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-pick-this-to-5.x

#1458 remove the note about dropping the database (#1454)
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, 5.x

#1450 Adding clarification that sub-admin roles should not be able to change their own privileges
  modules/ROOT/pages/tutorial/access-control.adoc
Labels: cherry-picked, 5.x

#1461 Remove legacy-backup and legacy-restore
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/index.adoc
Labels: cherry-pick-this-to-5.x

#1462 Remove legacy-backup and legacy-restore (#1461)
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/index.adoc
Labels: cherry-picked, 5.x

#1463 add link to cdc regarding unrecorded data changes
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, dev

#1464 add link to cdc regarding unrecorded data changes (#1463)
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked

#1457 Add a step to decouple the conf and data folders from the binaries
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x

#1465 Add a step to decouple the conf and data folders from the binaries (#1457)
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x
