Repository neo4j/docs-operations, pull requests merged in 2024-10, with the labels that each got.

#1844 Add version labels to the COSI sections
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#1845 Add version labels to the COSI sections (#1844)
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#1849 disabled section in ssl-fips page about docker image until docker image is finalised (#1848)
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
Labels: cherry-picked, 5.x

#1843 Add instructions on how to configure FIPS-compliant SSL
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4, do not cherry-pick

#1853 update the version to 4.4.38
  antora.yml
Labels: 4.4

#1840 Fix the image rendering
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
Labels: cherry-pick-this-to-5.x

#1854 Fix the image rendering (#1840)
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
Labels: cherry-picked, 5.x

#1821 Deprecate `existingDataSeedInstance` option to CREATE DATABASE
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: dev, team-cypher-operations, 5.25

#1855 Warn users that changing the store format also changes the built-in _id property and elementID
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-pick-this-to-5.x

#1856 Warn users that changing the store format also changes the built-in id property and elementID
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-picked, 5.x

#1846 Add the metric `<prefix>.cluster.raft.prune_index`
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: clustering, 5.25

#1852 Update the options' descriptions of the neo4j-admin commands according to the code
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 5.25

#1859 Added a new page for the backup inspect command.
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/index.adoc
  modules/ROOT/pages/backup-restore/inspect.adoc
Labels: clustering, 5.25

#1864 Fix backtick (#1860)
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, 5.x

#1866 Removed message about no TLS/SSL support for Minio.
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this forward, 5.x

#1867 Removed message about no TLS/SSL support for Minio. (#1866)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked

#1857 Clarify clustering ports and Docker tutorial for new v2 discovery protocol
  modules/ROOT/pages/configuration/ports.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-pick-this-to-5.x

#1868 Clarify clustering ports and Docker tutorial for new v2 discovery protocol (#1857)
  modules/ROOT/pages/configuration/ports.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked, 5.x

#1865 Changes to query log docs w.r.t. GQL codes
  modules/ROOT/pages/monitoring/logging.adoc
Labels: 5.25

#1869 Add an empty value for cloud provider
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x

#1870 Add footnote that --schema is not supported in 5.24
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#1862 remove before version 4.4
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-5.x

#1871 remove before version 4.4 (#1862)
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-picked, 5.x

#1874 Update constraints link following restructure in Cypher Manual
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#1873 Add an empty value for cloud provider (#1869)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#1876 Add footnote that --schema is not supported in 5.24 (#1870)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked

#1872 draganddrop4.4
  modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
Labels: 4.4

#1878 failureReason is deprecated in favour of errorInfo
  modules/ROOT/pages/monitoring/logging.adoc
Labels: 5.25

#1877 Add a note that Windows service runs as the LocalSystem account
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x

#1880 Add a note that Windows service runs as the LocalSystem account (#1877)
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x

#1882 Clarification on the use of JSON format
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-5.x

#1883 Update documentation to include recommendations for SWAP
  modules/ROOT/pages/performance/memory-configuration.adoc
Labels: cherry-pick-this-to-5.x

#1885 Update documentation to include recommendations for SWAP (#1883)
  modules/ROOT/pages/performance/memory-configuration.adoc
Labels: cherry-picked, 5.x

#1886 Add TLSv1.3 as an option in SSL framework section
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-5.x

#1888 Add TLSv1.3 as an option in SSL framework section (#1886)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1889 Add version to FIPS and backup inspect pages
  modules/ROOT/pages/backup-restore/inspect.adoc
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
Labels: 5.25

#1895 Improve the documentation around the use of ciphers
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/clustering/setup/encryption.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-5.x

#1894 Fix a Tarball installation issue
  modules/ROOT/pages/installation/linux/tarball.adoc
Labels: cherry-pick-this-to-5.x

#1893 Make `systemctl daemon-reload` a separate command
  modules/ROOT/pages/installation/linux/tarball.adoc
Labels: 4.4, cherry-pick-this-to-4.3, cherry-pick-this-to-4.2, cherry-pick-this-to-4.1

#1897 Fix a Tarball installation issue (#1894)
  modules/ROOT/pages/installation/linux/tarball.adoc
Labels: cherry-picked, 5.x

#1898 Make `systemctl daemon-reload` a separate command (#1893)
  modules/ROOT/pages/installation/linux/tarball.adoc
Labels: cherry-picked, 4.3

#1896 Improve the documentation around the use of ciphers (#1895)
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/clustering/setup/encryption.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1900 Remove deprecation from failureReason
  modules/ROOT/pages/monitoring/logging.adoc
Labels: 5.25

#1901 Make `systemctl daemon-reload` a separate command (#1893)
  modules/ROOT/pages/installation/linux/tarball.adoc
Labels: cherry-picked, 4.1

#1903 Swap tabs in the examples of v2 discovery
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
Labels: cherry-pick-this-to-5.x

#1905 Swap tabs in the examples of v2 discovery (#1903)
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
Labels: cherry-picked, 5.x

#1906 Add `CloudSeedProvider`
  modules/ROOT/pages/clustering/databases.adoc
Labels: 5.25

#1904 Add clarification that database field depends on the security event
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations

#1907 Add clarification that database field depends on the security event (#1904)
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, 5.x

#1891 Add info about the `--temp-path` option
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-pick-this-to-5.x

#1908 Add info about the `--temp-path` option (#1891)
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, 5.x

#1902 16,383 is the max length of tokens in characters
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: kernel, 5.25

#1892 Update the compatibility table of the dump and Aura versions
  modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
Labels: 4.3, do not cherry-pick

#1913 Fix a typo (#1910)
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: cherry-picked, 5.x

#1914 Update the example key-value pair to use / instead of :
  modules/ROOT/pages/docker/docker-compose-standalone.adoc
Labels: cherry-pick-this-to-5.x

#1915 Update the example key-value pair to use / instead of : (#1914)
  modules/ROOT/pages/docker/docker-compose-standalone.adoc
Labels: cherry-picked, 5.x

#1916 Add missing content to the Docker docs (#1804)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/docker/configuration.adoc
  modules/ROOT/pages/docker/docker-compose-standalone.adoc
  modules/ROOT/pages/docker/index.adoc
  modules/ROOT/pages/docker/introduction.adoc
  modules/ROOT/pages/docker/mounting-volumes.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/docker/plugins.adoc
Labels: 4.4

#1917 Docker secrets should only support neo4j variables
  modules/ROOT/pages/docker/docker-compose-standalone.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1918 Docker secrets should only support neo4j variables (#1917)
  modules/ROOT/pages/docker/docker-compose-standalone.adoc
Labels: cherry-picked, 5.x

#1919 Docker secrets should only support neo4j variables (#1917)
  modules/ROOT/pages/docker/docker-compose-standalone.adoc
Labels: 4.4, cherry-picked

#1920 Fix neo4j-version-exact
  antora.yml
Labels: cherry-pick-this-to-5.x

#1921 Fix neo4j-version-exact
  antora.yml
Labels: 5.x

#1922 Revert "Fix neo4j-version-exact"
  antora.yml
Labels: dev

#1912 Change aura-db-enterprise to aura-db-business-critical aura-db-dedicated
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations

#1926 Change aura-db-enterprise to aura-db-business-critical aura-db-dedicated (#1912)
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
Labels: cherry-picked, 5.x

#1928 Add a note saying the incremental import does not support multiple no…
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#1929 Merge dev into 5.x
  .github/workflows/docs-branch-checks.yml
  .github/workflows/docs-deploy-surge.yml
  .github/workflows/docs-teardown.yml
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/index.adoc
  modules/ROOT/pages/backup-restore/inspect.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: 5.x

#1930 update the exact version to 5.25.1
  antora.yml
Labels: 5.x, This branch only

#1909 Add deprecations and FileSeedProvider
  modules/ROOT/pages/clustering/databases.adoc
Labels: DO NOT MERGE, clustering, 5.26

#1861 Describe the semi-automated procedure that migrates Discovery Service V1 to V2.
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: clustering, 5.26

#1911 Allow parameters in CREATE/ALTER DATABASE TOPOLOGY
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/servers.adoc
Labels: team-cypher-operations, 5.26

#1887 Example of property-based access control using temporal value
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
Labels: team-cypher-operations, 5.26
