Repository neo4j/docs-operations, pull requests merged in 2024-07, with the labels that each got.

#1699 Fix group to role mapping section
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Labels: team-cypher-operations

#1694 Describe new lighthouse procedures
  modules/ROOT/pages/reference/procedures.adoc
Labels: clustering, 5.22

#1706 Fix group to role mapping section (#1699)
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#1707 Fix group to role mapping section (#1699)
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Labels: 4.4, cherry-picked

#1708 Block is the default for all newly-created databases
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
Labels: 5.22

#1710 Replace deprecated apt-key with keyrings
  modules/ROOT/pages/installation/linux/debian.adoc
Labels: cherry-pick-this-to-5.x

#1711 Replace deprecated apt-key with keyrings (#1710)
  modules/ROOT/pages/installation/linux/debian.adoc
Labels: cherry-picked, 5.x

#1714 Add --idle-timeout argument to cypher shell
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: dev, 5.22

#1715 update the exact version to 4.4.35
  antora.yml
Labels: 4.4

#1713 Fix broken link to Aura docs
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, cherry-pick-this-to-4.3

#1716 Fix broken link to Aura docs (#1713)
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-picked, 5.x

#1717 Fix the link to vpc isolation aura page
  modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
Labels: 4.4, cherry-picked, cherry-pick-this-to-4.3

#1718 Add a note that push to cloud does not support private linking
  modules/ROOT/pages/tools/neo4j-admin/push-to-cloud.adoc
Labels: cherry-picked, 4.3

#1719 Aggregate backup in neo4j-admin helm chart
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x, 5.21

#1721 Aggregate backup in neo4j-admin helm chart (#1719)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#1720 update netty version
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 4.4

#1722 db.format default value is changed to block
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.22

#1689 Update neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-pick-this forward

#1723 Update neo4j-admin-import.adoc (#1689)
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-picked, dev

#1729 dropping all capabilities of containerSecurityContext
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
Labels: cherry-pick-this-to-5.x, 5.21

#1730 dropping all capabilities of containerSecurityContext (#1729)
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
Labels: cherry-picked, 5.x

#1724 clarifying that `auth_cache_ttl` abd `use_ttl` applies to OIDC too
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, team-cypher-operations

#1732 clarifying that `auth_cache_ttl` abd `use_ttl` applies to OIDC too (#1724)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1733 clarifying that `auth_cache_ttl` abd `use_ttl` applies to OIDC too (#1724)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 4.4, cherry-picked

#1736 Remove the deprecated procedures from the list
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1738 Remove the deprecated procedures from the list (#1736)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1741 update version to 5.23
  antora.yml
Labels: 5.23

#1725 Deprecate uncordon procedure
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.23

#1727 Remove removed fields from showParallelDiscoveryState
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.23

#1728 Add the new config `db.cluster.raft.so_keepalive_enabled`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: DO NOT MERGE, 5.23

#1726 Add a new config `server.bolt.additional_listen_addresses`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.23

#1737 genAI is available in CE
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/plugins.adoc
Labels: DO NOT MERGE, 5.23

#1744 Update the exact version to 4.4.36
  antora.yml
Labels: 4.4

#1746 updated ssl+netty compatibility table for 5x
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-5.x
