Repository neo4j/docs-operations, pull requests merged in 2024-09, with the labels that each got.

#1800 Add details about the initial password
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: 4.4

#1801 Netty and tcnative files are included in the /lib directory from v5.21
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-pick-this-to-5.x

#1803 Netty and tcnative files are included in the /lib directory from v5.21 (#1801)
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1743 Add seed docs for Azure
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/partials/azb-credentials.adoc
Labels: 5.24

#1804 Add docker compose documentation
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/docker/docker-compose-standalone.adoc
  modules/ROOT/pages/docker/index.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1767 Improve a few steps configuring SSO on Azure
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-pick-this-to-5.x

#1809 Improve a few steps configuring SSO on Azure (#1767)
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked, 5.x

#1793 Explain the importance of checkpointing for backups
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1811 Explain the importance of checkpointing for backups (#1793)
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: 4.4, cherry-picked

#1813 Update default value for server.http_enabled_modules (#1812)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1814 Update the v.number to 4.4.37
  antora.yml
Labels: 4.4

#1815 Add a note about clusters with 2 members
  modules/ROOT/pages/clustering/setup/deploy.adoc
Labels: cherry-pick-this-to-5.x, clustering

#1817 Add a note about clusters with 2 members (#1815)
  modules/ROOT/pages/clustering/setup/deploy.adoc
Labels: cherry-picked, 5.x

#1818 add version label to property rules
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations

#1816 Add new procedures `dbms.cluster.recreateDatabase`, `dbms.cluster.statusCheck`
  modules/ROOT/pages/reference/procedures.adoc
Labels: clustering, 5.24

#1808 Added detail on backup compression flag
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: 5.24

#1819 Add docs on the recreate procedure
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/index.adoc
Labels: clustering, 5.24

#1805 Add `DROP DATABASE name CASCADE ALIASES`
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/delete-composite-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: team-cypher-operations, 5.24

#1823 Docs for the rafted status check procedure.
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
Labels: clustering, 5.24

#1745 User Auth Providers
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
  modules/ROOT/pages/authentication-authorization/auth-providers.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: team-cypher-operations, 5.24

#1827 Fix the labels on the Cluster status check page, add info to the clustering intro page
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
Labels: 5.24

#1822 Add `--schema` to the neo4j-admin import tool
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 5.24

#1828 5.24 release - cherry-picks
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
  modules/ROOT/pages/authentication-authorization/auth-providers.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/delete-composite-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
  modules/ROOT/pages/docker/docker-compose-standalone.adoc
  modules/ROOT/pages/docker/index.adoc
  modules/ROOT/pages/reference/procedures.adoc
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
  modules/ROOT/partials/azb-credentials.adoc
Labels: cherry-picked, 5.x

#1829 add missing stuff
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.x, This branch only

#1833 Update preview version to 5.25
  antora.yml
Labels: 5.25

#1835 Add the version from which `--temp-path` is available (#1834)
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, 5.x

#1802 Update steps on how to recover pswd
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations

#1837 Update steps on how to recover pswd (#1802)
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
Labels: cherry-picked, 5.x

#1836 Edit status check
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
Labels: cherry-pick-this-to-5.x, dev

#1838 Edit status check (#1836)
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
Labels: cherry-picked, 5.x

#1841 New SSL instructions for FIPS compatibility (#1806)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/docker/introduction.adoc
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1826 Show columns clarifications
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
Labels: cherry-pick-this-to-5.x, dev, team-cypher-operations

#1842 Show columns clarifications (#1826)
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
Labels: cherry-picked, 5.x
