Repository neo4j/docs-operations, pull requests merged in 2024-01, with the labels that each got.

#1244 Deploy an analytics cluster using the Neo4j Helm chart
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
  modules/ROOT/pages/kubernetes/quickstart-analytics-cluster.adoc
Labels: cherry-pick-this-to-5.x, 5.14

#1296 Deploy an analytics cluster using the Neo4j Helm chart (#1244)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/plugins.adoc
  modules/ROOT/pages/kubernetes/quickstart-analytics-cluster.adoc
Labels: cherry-picked, 5.x

#1295 db.index.vector.createNodeIndex replaced by CREATE VECTOR INDEX
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1297 db.index.vector.createNodeIndex replaced by CREATE VECTOR INDEX (#1295)
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1282 Clarify lock note again
  modules/ROOT/pages/database-internals/locks-deadlocks.adoc
Labels: 5.16

#1271 Add support for Amazon Linux 2023 AMI
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-pick-this-to-5.x

#1299 Add support for Amazon Linux 2023 AMI (#1271)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#1298 update instructions on how to recover admin user and password in a cl…
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  package-lock.json
Labels: cherry-pick-this-to-5.x, clustering

#1303 update instructions on how to recover admin user and password in a cl…
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
Labels: cherry-picked, clustering

#1181 Update the procedure descriptions
  modules/ROOT/images/cosine_similarity_equation.svg
  modules/ROOT/images/cosine_similarity_equation.tex
  modules/ROOT/images/euclidean_similarity_equation.svg
  modules/ROOT/images/euclidean_similarity_equation.tex
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-pick-this-to-5.x

#1304 Add a missing space
  modules/ROOT/pages/database-administration/index.adoc
Labels: cherry-pick-this-to-5.x

#1305 add details about topology
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-pick-this-to-5.x, clustering

#1308 add details about topology (#1305)
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, clustering

#1301 Rename Neo4j connectors to network connectors to differentiate them from Kafka, Spark, etc.
  modules/ROOT/pages/configuration/connectors.adoc
Labels: cherry-pick-this-to-5.x

#1309 Rename Neo4j connectors to network connectors to differentiate them from Kafka, Spark, etc. (#1301)
  modules/ROOT/pages/configuration/connectors.adoc
Labels: cherry-picked, 5.x

#1310 Remove the EE label from the backup and restore index page
  modules/ROOT/pages/backup-restore/index.adoc
Labels: cherry-pick-this-to-5.x

#1311 Remove the EE label from the backup and restore index page (#1310)
  modules/ROOT/pages/backup-restore/index.adoc
Labels: cherry-picked, 5.x

#1307 Restructure the installation page
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/installation/index.adoc
  modules/ROOT/pages/installation/neo4j-browser.adoc
  modules/ROOT/pages/tools/index.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1312 Fix duplicated entry for `page_cache.page_cancelled_faults` metric
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x, kernel

#1314 clarify topology (#1313)
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, clustering

#1315 Update the procedure descriptions (#1181)
  modules/ROOT/images/cosine_similarity_equation.svg
  modules/ROOT/images/cosine_similarity_equation.tex
  modules/ROOT/images/euclidean_similarity_equation.svg
  modules/ROOT/images/euclidean_similarity_equation.tex
  modules/ROOT/pages/reference/procedures.adoc
Labels: cherry-picked, 5.x

#1300 Update the default value of dbms.record_format
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 4.4

#1317 Fix duplicated entry for `page_cache.page_cancelled_faults` metric
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#1270 Removing enterprise label from cloud deployment pages
  modules/ROOT/pages/cloud-deployments/index.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
Labels: cherry-pick-this-to-5.x

#1318 Restructure the installation page
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/installation/index.adoc
  modules/ROOT/pages/installation/neo4j-browser.adoc
  modules/ROOT/pages/tools/index.adoc
Labels: 5.x, copied

#1319 Removing enterprise label from cloud deployment pages #1270
  modules/ROOT/pages/cloud-deployments/index.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
Labels: cherry-picked

#1320 Fixing typo in url
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
Labels: bug

#1323 Report command handles several dbs and allows for specifying which
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
Labels: 5.16

#1222 Neo4-admin-backup-globbing
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: 5.16

#1326 Fix wrong env variables to deploy Neo4j in Docker (#1325)
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked, 5.x

#1329 Add a note about Idp connectivity
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations

#1332 Rename the section according to the TOC
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-pick-this-to-5.x

#1333 Add a note about Idp connectivity (#1329)
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Labels: cherry-picked, 5.x

#1334 Rename the section according to the TOC (#1332)
  modules/ROOT/pages/configuration/index.adoc
Labels: cherry-picked, 5.x

#1336 Tag deallocated state with version
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-pick-this-to-5.x, 5.x, clustering

#1331 Add uninstallation steps
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-backward

#1341 Add uninstallation steps (#1331)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked

#1342 Add uninstallation steps (#1331)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked

#1343 Add uninstallation steps (#1331)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked

#1344 Add uninstallation steps (#1331)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked

#1345 Add uninstallation steps (#1331)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked

#1346 Add uninstallation steps (#1331)
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked

#1351 Cherry picks for the 5.16 release. Part 2
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-internals/index.adoc
  modules/ROOT/pages/database-internals/locks-deadlocks.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/performance/space-reuse.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-report.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
Labels: cherry-picked, 5.x, 5.16

#1340 fix mismatching configs
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1356 fix mismatching configs (#1340)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1359 Fix a typo in server.memory.pagecache.size doc string
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1360 fix a typo
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1353 Mix ID types when using neo4j-admin import
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x

#1354 update the backup and restore commands
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-pick-this-to-5.x

#1364 update the backup and restore commands (#1354)
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, 5.x

#1363 Mix ID types when using neo4j-admin import (#1353)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked, 5.x

#1366 Add a link from configure retention to dynamic settings
  modules/ROOT/pages/database-internals/transaction-logs.adoc
Labels: cherry-pick-this-to-5.x

#1368 Add a link from configure retention to dynamic settings
  modules/ROOT/pages/database-internals/transaction-logs.adoc
Labels: cherry-picked, 5.x

#1358 Add a metric for block format
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x

#1365 Add new metrics to count page flushed by background evictor
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: kernel, 5.17

#1371 Remove duplication of JVM heap initial size config
  modules/ROOT/pages/kubernetes/operations/scaling.adoc
Labels: cherry-pick-this-to-5.x

#1370 Fixing persisting 404 error
  modules/ROOT/pages/database-administration/index.adoc
Labels: cherry-pick-this-to-5.x

#1374 add a page alias for deploy a cluster
  modules/ROOT/pages/clustering/setup/deploy.adoc
Labels: cherry-pick-this-to-5.x

#1375 add a page alias for deploy a cluster
  modules/ROOT/pages/clustering/setup/deploy.adoc
Labels: cherry-picked, 5.x

#1377 fix lxref instead of xref in immutable privileges tutorial (#1347)
  modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
Labels: cherry-picked, 5.x

#1378 update the description of db.format to include block
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1379 update the description of db.format to include block
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#1357 Document dbms.cluster.network.connect_timeout
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: clustering, 5.17

#1382 Add block format to copy, migrate, and configs (#1349)
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
Labels: cherry-picked, 5.x

#1380 update the description of --from-path
  modules/ROOT/pages/tools/neo4j-admin/consistency-checker.adoc
Labels: 5.17

#1387 Fix a typo in k8s docs
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-pick-this-to-5.x

#1388 Fix a typo in k8s docs
  modules/ROOT/pages/kubernetes/accessing-neo4j-ingress.adoc
Labels: cherry-picked, 5.x

#1391 update exact version to 4.4.30
  antora.yml
Labels: 4.4
