Repository neo4j/docs-operations, pull requests merged in 2024-12, with the labels that each got.

#2001 Document immutable roles
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/immutable-roles-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/authentication-authorization/privileges-immutable.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
Labels: 5.26

#2003 Merge dev into 5.x
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/immutable-roles-privileges.adoc
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
  modules/ROOT/pages/authentication-authorization/privileges-immutable.adoc
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/routing-decisions.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/database-internals/transaction-logs.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/installation/requirements.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/performance/index-configuration.adoc
  modules/ROOT/pages/performance/space-reuse.adoc
  modules/ROOT/pages/performance/statistics-execution-plans.adoc
  modules/ROOT/pages/procedures.adoc
  modules/ROOT/pages/reference/index.adoc
  modules/ROOT/pages/reference/procedures.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-immutable-privileges.adoc
Labels: 5.x

#1973 Tie up the Database internals section with the v4.4
  modules/ROOT/pages/database-internals/checkpointing.adoc
  modules/ROOT/pages/database-internals/index.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-pick-this-to-5.x

#1952 Allow database names to start with a digit
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
Labels: dev, team-cypher-operations, Dependencies w. other PR, 2025.01

#1948 Disallow unquoted database names with dot
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
Labels: team-cypher-operations, 2025.01, Cypher 25

#2006 Add note that latest backup/chain cannot be used together
  modules/ROOT/pages/backup-restore/inspect.adoc
Labels: dev, 2025.01

#1990 Remove GZip compression
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: clustering, 2025.01

#1981 Change default for shutdown on panic setting
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 2025.01

#2004 Bump dev to 2025.01
  antora.yml
  modules/ROOT/pages/index.adoc
  preview.yml
  publish.yml
Labels: 2025.01

#2012 Remove anonymous from usage data
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/installation/index.adoc
  modules/ROOT/pages/introduction.adoc
Labels: cherry-pick-this-to-5.x

#2015 Correct json xml
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, 5.x

#2013 Remove anonymous from usage data (#2012)
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/installation/index.adoc
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked, 5.x

#2014 Fix the default Bolt port
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: cherry-pick-this-to-5.x

#2000 Update warning on how and when to use the `unbind` command
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
Labels: cherry-pick-this-to-5.x, clustering

#2017 Update the version to 4.4.40
  antora.yml
Labels: 4.4

#2018 Fix the default Bolt port (#2014)
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: cherry-picked, 5.x

#2019 Update warning on how and when to use the `unbind` command (#2000)
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
Labels: cherry-picked, 5.x

#2010 Prefer seed from uri over load
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
Labels: cherry-pick-this-to-5.x

#2024 Prefer seed from uri
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
Labels: 5.x, copied

#1890 Rewrite disaster recovery based on recreate and status check
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
Labels: cherry-pick-this-to-5.x, clustering

#2023 Fix the --env NEO4J_AUTH=neo4j/
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/docker/configuration.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/kubernetes/operations/image-pull-secret.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-pick-this-to-5.x

#2025 Fix the --env NEO4J_AUTH=neo4j/ (#2023)
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
  modules/ROOT/pages/docker/configuration.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/kubernetes/operations/image-pull-secret.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked, 5.x

#2027 Rewrite disaster recovery based on recreate and status check (#1890)
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
Labels: cherry-picked, 5.x

#1985 Add new unquarantine procedure + deprecate quarantine
  modules/ROOT/pages/database-administration/standard-databases/errors.adoc
  modules/ROOT/pages/procedures.adoc
Labels: clustering, 2025.01

#2005 Add description to fields in RaftedStatusCheck procedure
  modules/ROOT/pages/clustering/monitoring/status-check.adoc
  modules/ROOT/pages/procedures.adoc
Labels: clustering, 2025.01

#2026 Update the disaster recovery page to address feedback
  modules/ROOT/pages/clustering/disaster-recovery.adoc
Labels: cherry-pick-this-to-5.x

#2021 Add a note that migration from Aligned with "book tokens" to Block is not supported
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-pick-this-to-5.x

#2008 Add GQLSTATUS code to Neo. code
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
Labels: cherry-pick-this-to-5.x

#2031 Revert "Disallow unquoted database names with dot"
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
Labels: 2025.01

#2032 Add GQLSTATUS code to Neo. code (#2008)
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
Labels: cherry-picked, 5.x
