Repository neo4j/docs-operations, pull requests merged in 2024-08, with the labels that each got.

#1750 updated ssl+netty compatibility table for 5x
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: cherry-picked, 5.x

#1749 Update settings related to discovery service v2
  modules/ROOT/pages/clustering/settings.adoc
Labels: 5.23

#1747 Update the first page of the Clustering section
  modules/ROOT/pages/clustering/clustering-advanced/index.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/setup/routing.adoc
Labels: cherry-pick-this-to-5.x

#1751 Update the first page of the Clustering section (#1747)
  modules/ROOT/pages/clustering/clustering-advanced/index.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/setup/routing.adoc
Labels: cherry-picked, 5.x

#1752 Add EE label to cloud storage sections of the `dump` and `load` commands
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: cherry-pick-this-to-5.x

#1753 Add EE label to cloud storage sections of the `dump` and `load` commands (#1752)
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: cherry-picked, 5.x

#1739 Discovery service V1 to V2 upgrading guide
  modules/ROOT/images/discovery-service/in-place-1-v1-over-v2.png
  modules/ROOT/images/discovery-service/in-place-1-v2-over-v1.png
  modules/ROOT/images/discovery-service/in-place-123-v2-only.png
  modules/ROOT/images/discovery-service/in-place-23-v1-over-v2.png
  modules/ROOT/images/discovery-service/in-place-23-v2-over-v1.png
  modules/ROOT/images/discovery-service/v1-only.png
  modules/ROOT/images/discovery-service/v1_over_v2.png
  modules/ROOT/images/discovery-service/v2_only.png
  modules/ROOT/images/discovery-service/v2_over_v1.png
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: 5.23

#1756 Lighthouse - minor improvements
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: 5.23

#1697 Adding new limited allocation procedures
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: clustering, 5.23

#1759 add info that backup file can also be uploaded to aura
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-5.x, dev

#1754 Update instructions on how to set up a basic cluster with DS V2
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
Labels: clustering, 5.23

#1757 Update the page on how to deploy an analytics cluster with DS V2
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
Labels: clustering, 5.23

#1758 Update instructions on how to move from single deployment to cluster
  modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
Labels: clustering, 5.23

#1761 Remove accidental 'git'
  modules/ROOT/pages/clustering/databases.adoc
Labels: clustering, 5.23

#1762 Add a caution about REALLOCATE DATABASES moving too much
  modules/ROOT/pages/clustering/databases.adoc
Labels: clustering, 5.23

#1763 adding health warning about insecure protocols for LOAD CSV
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
Labels: dev, 5.23

#1734 use a bucket policy to grant permissions to access the bucket
  modules/ROOT/partials/aws-s3-credentials.adoc
Labels: cherry-pick-this-to-5.x

#1766 use a bucket policy to grant permissions to access the bucket (#1734)
  modules/ROOT/partials/aws-s3-credentials.adoc
Labels: cherry-picked, 5.x

#1735 High-limit and standard format are deprecated
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 5.23

#1764 Update valid values of the Bolt related configs
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.23

#1769 Remove commented out labels in favor of roles.
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x

#1775 add mention of 5.22 when backup fil was allowed
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-pick-this-to-5.x, dev

#1776 add mention of 5.22 when backup fil was allowed (#1775)
  modules/ROOT/pages/tools/neo4j-admin/upload-to-aura.adoc
Labels: cherry-picked, 5.x

#1773 Remove the config `db.logs.query.time_logging_enabled`
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-5.x

#1777 Update the page on how to delete db
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
Labels: cherry-pick-this-to-5.x

#1778 Remove the config `db.logs.query.time_logging_enabled` (#1773)
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, 5.x

#1780 Fix the asciidoc syntax
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: 5.23

#1782 Change http to https in links to external sites
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x

#1783 Change http to https in links to external sites (#1782)
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x

#1784 Change http to https in links to external sites
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: 4.4

#1786 Release 5.23. Part 2
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/discovery-service/in-place-1-v1-over-v2.png
  modules/ROOT/images/discovery-service/in-place-1-v2-over-v1.png
  modules/ROOT/images/discovery-service/in-place-123-v2-only.png
  modules/ROOT/images/discovery-service/in-place-23-v1-over-v2.png
  modules/ROOT/images/discovery-service/in-place-23-v2-over-v1.png
  modules/ROOT/images/discovery-service/v1-only.png
  modules/ROOT/images/discovery-service/v1_over_v2.png
  modules/ROOT/images/discovery-service/v2_only.png
  modules/ROOT/images/discovery-service/v2_over_v1.png
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/clustering/settings.adoc
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/clustering/setup/single-to-cluster.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/plugins.adoc
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.x

#1787 5.23 release. Part 3
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 5.x

#1788 Release 5.23. Part 4
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: 5.x

#1789 Update the version to 5.24
  antora.yml
Labels: 5.24

#1768 Add docs related to public --temp-path option in backup related commands
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: clustering, 5.24

#1791 Change the signature for the `dbms.cluster.checkConnectivity` procedure
  modules/ROOT/pages/reference/procedures.adoc
Labels: 5.24

#1790 Add a small clarification on using sub-CA for a cluster
  modules/ROOT/pages/clustering/setup/encryption.adoc
Labels: cherry-pick-this-to-5.x

#1781 Improve the config example of Azure SSO for Kubernetes
  modules/ROOT/pages/kubernetes/authentication-authorization.adoc
Labels: cherry-pick-this-to-5.x, DO NOT MERGE

#1795 Improve the config example of Azure SSO for Kubernetes (#1781)
  modules/ROOT/pages/kubernetes/authentication-authorization.adoc
Labels: cherry-picked, 5.x

#1792 Add details about the initial password
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x

#1797 Add details about the initial password (#1792)
  modules/ROOT/pages/installation/linux/systemd.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x

#1796 Fix the default name of `listen_address`
  modules/ROOT/pages/configuration/connectors.adoc
Labels: cherry-pick-this-to-5.x, kernel

#1798 Fix the default name of `listen_address` (#1796)
  modules/ROOT/pages/configuration/connectors.adoc
Labels: cherry-picked, 5.x

#1799 Fix the default name of `listen_address`
  modules/ROOT/pages/configuration/connectors.adoc
Labels: 4.4, copied
