Repository neo4j/docs-operations, pull requests merged in 2025-07, with the labels that each got.

#2459 Add `causal_clustering.load_balancing.config.server_policies` to the ref page
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 4.4, copied

#2372 Cypher25 default language
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/configuration/cypher-version-configuration.adoc
  modules/ROOT/pages/configuration/index.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/alter-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/create-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/list-composite-databases.adoc
  modules/ROOT/pages/database-administration/composite-databases/start-stop-composite-databases.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/configuration-parameters.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/start-stop-databases.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/partials/cypher-versions.adoc
  modules/ROOT/partials/view-cypher-version.adoc
Labels: Cypher 25, cypher-25-branch

#2464 Update to 2025.07
  antora.yml
Labels: 2025.07

#2468 update the checkpoint messages
  modules/ROOT/pages/database-internals/checkpointing.adoc
Labels: auto-cherry-pick-to-main

#2472 Improve enabling command expansion section (#2470)
  modules/ROOT/pages/configuration/command-expansion.adoc
Labels: cherry-picked

#2476 Update the Set up the repository for Linux rpm (#2475)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked

#2477 Update the Set up the repository for Linux rpm (#2475)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked

#2469 Fix the helm install backup-name neo4j/neo4j-admin command
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2482 Fix the helm install backup-name neo4j/neo4j-admin command (#2469)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked

#2485 Update exact neo4j version to 2025.06.2
  antora.yml
Labels: This branch only

#2478 Remove against the system database from Handy tips
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2487 Remove against the system database from Handy tips (#2478)
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
Labels: cherry-picked

#2489 Clarify version for parquet header support.
  modules/ROOT/pages/import.adoc
Labels: auto-cherry-pick, auto-cherry-pick-to-main

#2491 Clarify version for parquet header support. (#2489)
  modules/ROOT/pages/import.adoc
Labels: cherry-picked

#2492 Update Kubernetes oprations manual for backups (#2462)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked

#2488 Restyle RBAC limitations and warn about use of fail-open DENY semantics
  modules/ROOT/pages/authentication-authorization/limitations.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2501 Server tags are not used during database allocation (#2499)
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-picked

#2503 Fix the restore metadata paths (#2498)
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
Labels: cherry-picked

#2500 `DEALLOCATING` is an irreversible server state
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-pick-this-to-5.x, dev, cherry-pick-this-to-main

#2508 Remove externalService and add services.neo4j.spec.loadBalancerIP (#2494)
  modules/ROOT/pages/kubernetes/accessing-neo4j.adoc
  modules/ROOT/pages/kubernetes/configuration.adoc
Labels: cherry-picked

#2511 Improve the table formatting (#2453)
  modules/ROOT/pages/introduction.adoc
Labels: cherry-picked, main
