Repository neo4j/docs-operations, pull requests merged in 2025-09, with the labels that each got.

#2558 Fix the name of `neo4j-admin server unbind` cmd
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2560 Fix the name of `neo4j-admin server unbind` cmd (#2558)
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-picked, main

#2563 Publish 2025.08 release
  antora.yml
  modules/ROOT/images/privileges_grant_and_deny_syntax_database_privileges.svg
  modules/ROOT/images/privileges_hierarchy_database.svg
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/cypher-shell.adoc
Labels: This branch only, main, 2025.08

#2556 Update links to the Browser docs
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/cypher-shell.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/procedures.adoc
  modules/ROOT/pages/security/browser.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2568 Update links to the Browser docs (#2556)
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/procedures.adoc
  modules/ROOT/pages/security/browser.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-picked, 5.x

#2572 Remove problematic part from `unbind` docs (#2570)
  modules/ROOT/pages/tools/neo4j-admin/unbind.adoc
Labels: cherry-picked, 5.x

#2551 Clarify using of the `ALTER SERVER` options
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-pick-this-to-5.x, clustering, cherry-pick-this-to-main

#2575 Clarify using of the `ALTER SERVER` options (#2551)
  modules/ROOT/pages/clustering/servers.adoc
Labels: cherry-picked, 5.x

#2580 Refine filesystem requirements (#2578)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, 5.x

#2582 Render example URI as code instead of link
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-pick-this-to-main

#2586 Render example URI as code instead of link (#2582)
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked, 5.x

#2599 Render an example link as code
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2603 Restore page-aliases for the pages on neo4j-admin cmds (#2600)
  modules/ROOT/pages/backup-restore/consistency-checker.adoc
  modules/ROOT/pages/clustering/unbind.adoc
  modules/ROOT/pages/configuration/migrate-configuration.adoc
  modules/ROOT/pages/configuration/neo4j-admin-memrec.adoc
  modules/ROOT/pages/configuration/validate-config.adoc
  modules/ROOT/pages/cypher-shell.adoc
  modules/ROOT/pages/database-administration/standard-databases/migrate-database.adoc
  modules/ROOT/pages/database-internals/neo4j-admin-store-info.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/neo4j-admin-neo4j-cli.adoc
Labels: cherry-picked, main

#2601 Document how to recover unrecovered full backup
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/consistency-checker.adoc
Labels: cherry-pick-this-to-main

#2606 Document how to recover unrecovered full backup (#2601)
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/consistency-checker.adoc
Labels: cherry-picked, main

#2605 Remove the page on deploying cluster across AKS clusters
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/multi-dc-cc-aks.png
  modules/ROOT/pages/kubernetes/index.adoc
  modules/ROOT/pages/kubernetes/multi-dc-cluster/aks.adoc
Labels: 5.x, copied

#2607 run consistency check against a specific full backup when many fulls …
  modules/ROOT/pages/backup-restore/consistency-checker.adoc
Labels: 2025.09

#2584 Document `--remote-address-resolution`
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: 2025.09

#2614 Fixing color of text to match the other nodes
  modules/ROOT/images/cluster-on-k8s.svg
Labels: bug

#2622 Fix some typos in the configuration settings and update one description (#2620)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked

#2624 Publish 2025.09 release
  antora.yml
  modules/ROOT/pages/backup-restore/consistency-checker.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: This branch only, main

#2625 Bump the version number to 2025.10
  antora.yml
Labels: 2025.10

#2541 Images refresh batch 2
  modules/ROOT/images/backup-chain-aggregate.png
  modules/ROOT/images/privileges-grant-and-deny-syntax-database-privileges.svg
  modules/ROOT/images/privileges-grant-and-deny-syntax-dbms-privileges.svg
  modules/ROOT/images/privileges-grant-and-deny-syntax-load-privileges.svg
  modules/ROOT/images/privileges-grant-and-deny-syntax.svg
  modules/ROOT/images/privileges-hierarchy-database.svg
  modules/ROOT/images/privileges-hierarchy-dbms.svg
  modules/ROOT/images/privileges-hierarchy.svg
  modules/ROOT/images/privileges-on-graph-syntax.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax_database_privileges.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_grant_and_deny_syntax_load_privileges.svg
  modules/ROOT/images/privileges_hierarchy.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
  modules/ROOT/images/privileges_on_graph_syntax.svg
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/kubernetes/quickstart-standalone/server-setup.adoc
Labels: cherry-pick-this-to-main
