Repository neo4j/docs-operations, pull requests merged in 2025-05, with the labels that each got.

#2308 Anchor fixes (#2306)
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, cypher-25-branch

#2307 Anchor fixes (#2306)
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, main

#2309 Anchor fixes (#2306)
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, 5.x

#2290 Add page-aliases following the removal of the Tools section
  modules/ROOT/pages/backup-restore/consistency-checker.adoc
  modules/ROOT/pages/clustering/clustering-advanced/unbind.adoc
  modules/ROOT/pages/configuration/migrate-configuration.adoc
  modules/ROOT/pages/configuration/neo4j-admin-memrec.adoc
  modules/ROOT/pages/configuration/validate-config.adoc
  modules/ROOT/pages/cypher-shell.adoc
  modules/ROOT/pages/database-administration/standard-databases/migrate-database.adoc
  modules/ROOT/pages/database-administration/standard-databases/upload-to-aura.adoc
  modules/ROOT/pages/database-internals/neo4j-admin-store-info.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/monitoring/neo4j-admin-report.adoc
  modules/ROOT/pages/neo4j-admin-neo4j-cli.adoc
Labels: This branch only, main

#2247 Fix example codes for Neo4j cluster on AKS
  modules/ROOT/pages/kubernetes/multi-dc-cluster/aks.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2310 Cypher25 ddm no block
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, cypher-25-branch

#2311 Document metrics reporting -1 on block format.
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-picked, 5.x

#2312 Update the exact version to 5.26.6
  antora.yml
Labels: 5.x, This branch only

#2314 Fix example codes for Neo4j cluster on AKS (#2247)
  modules/ROOT/pages/kubernetes/multi-dc-cluster/aks.adoc
Labels: cherry-picked, main

#2287 Remove `useExisting` option; polish examples & page
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Labels: clustering, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2289 Dev memory config vector indexes
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/performance/index.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/performance/vector-index-memory-configuration.adoc
Labels: cherry-pick-this-to-main, cherry-pick-this-to-cypher-25, team-kernel

#2321 Dev memory config vector indexes (#2289)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/performance/index.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/performance/vector-index-memory-configuration.adoc
Labels: cherry-picked, cypher-25-branch

#2317 Fix a few broken links to the Cypher manual
  models/hospital/access-control-old.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2322 Fix a few broken links to the Cypher manual (#2317)
  models/hospital/access-control-old.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: cherry-picked

#2323 Fix a few broken links to the Cypher manual (#2317)
  models/hospital/access-control-old.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: cherry-picked, cypher-25-branch

#2318 Add a note that obfuscate literals does not work with malformed queries
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2324 Add a note that obfuscate literals does not work with malformed queries (#2318)
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked

#2326 Add a note that obfuscate literals does not work with malformed queries (#2318)
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, 5.x

#2316 Document `server.backup.advertised_address` and deprecate `dbms.routing.load_balancing.plugin`
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: clustering, cherry-pick-this-to-cypher-25, 2025.05

#2332 Document `server.backup.advertised_address` and deprecate `dbms.routi…
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, cypher-25-branch

#2329 Fix group-role mapping for LDAP integration
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, team-cypher-operations, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2335 Fix group-role mapping for LDAP integration (#2329)
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
Labels: cherry-picked, main

#2337 Fix group-role mapping for LDAP integration (#2329)
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
Labels: cherry-picked, 5.x

#2338 Fix group-role mapping for LDAP integration (#2329)
  modules/ROOT/pages/authentication-authorization/ldap-integration.adoc
Labels: 4.4, cherry-picked

#2339 Fix formatting of the listing db output
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2340 Fix formatting of the listing db output (#2339)
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Labels: cherry-picked, main

#2341 Fix formatting of the listing db output (#2339)
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Labels: cherry-picked, cypher-25-branch

#2342 Fix formatting of the listing db output (#2339)
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Labels: cherry-picked, 5.x

#2344 Bump version number to 4.4.43
  antora.yml
Labels: 4.4, This branch only

#2345 Fix cluster related Docker env variables
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2346 Fix cluster related Docker env variables
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: 5.x, This branch only

#2347 Fix cluster related Docker env variables (#2345)
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked, main

#2348 Fix cluster related Docker env variables (#2345)
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
Labels: cherry-picked, cypher-25-branch

#2343 Clarify FIPS cipher configuration
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2350 Error messages are deprecated (#2330)
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: cherry-picked

#2351 Error messages are deprecated (#2330)
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: cherry-picked, cypher-25-branch

#2353 Clarify FIPS cipher configuration (#2343)
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
Labels: cherry-picked, cypher-25-branch

#2352 Clarify FIPS cipher configuration (#2343)
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
Labels: cherry-picked, main

#2354 Clarify FIPS cipher configuration (#2343)
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
Labels: cherry-picked, 5.x

#2356 Fix grammar mistakes
  modules/ROOT/pages/security/ssl-fips-compatibility.adoc
Labels: main

#2357 Fix `xref` related syntax (#2349)
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/database-administration/queries.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-picked, cypher-25-branch

#2327 Align cypher shell with the codebase
  modules/ROOT/pages/cypher-shell.adoc
Labels: cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2334 Clarify on how to manage Neo4j cluster with ASG on AWS
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2359 Clarify on how to manage Neo4j cluster with ASG on AWS (#2334)
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
Labels: cherry-picked, cypher-25-branch

#2360 Clarify on how to manage Neo4j cluster with ASG on AWS (#2334)
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
Labels: cherry-picked, main

#2361 Clarify on how to manage Neo4j cluster with ASG on AWS (#2334)
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
Labels: cherry-picked, 5.x

#2116 Add new setting on a default Cypher
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: team-cypher-operations, Cypher 25

#2375 Clarify which seed providers can be used with `restoreUntil` (#2368)
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Labels: This branch only, cypher-25-branch
