Repository neo4j/docs-operations, pull requests merged in 2025-10, with the labels that each got.

#2630 4.4 update version
  antora.yml
Labels: This branch only

#2633 Third batch of refreshed images (#2545)
  modules/ROOT/images/federation.svg
  modules/ROOT/images/flat-vs-segmented-network.svg
  modules/ROOT/images/neo4j-memory-management.svg
  modules/ROOT/images/northwind-composite-datamodel.svg
  modules/ROOT/images/northwind-datamodel.svg
  modules/ROOT/images/security-example.png
  modules/ROOT/images/security-example.svg
  modules/ROOT/images/sharding2.svg
  modules/ROOT/pages/tutorial/access-control.adoc
Labels: cherry-picked

#2626 Document config_server.metrics.deny_filter
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 2025.10

#2635 Fix the link to the Aura console (#2628)
  modules/ROOT/pages/installation/osx.adoc
Labels: cherry-picked, main

#2637 Update descriptions of the `initial.` settings (#2587)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#2627 Improve the Configure plugins page and document Fleet management
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2644 Improve the Configure plugins page and document Fleet management (#2627)
  modules/ROOT/pages/configuration/plugins.adoc
Labels: cherry-picked

#2623 Clarify situation when enabling servers
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/clustering/multi-region-deployment/multi-data-center-routing.adoc
  modules/ROOT/pages/clustering/servers.adoc
  modules/ROOT/pages/clustering/setup/analytics-cluster.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, clustering, cherry-pick-this-to-main
