Repository neo4j/docs-operations, pull requests merged in 2025-03, with the labels that each got.

#2134 Add section about Parquet header in admin import.
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 2025.03

#2154 Clarify that CREATE OR REPLACE DB deletes indexes and constraints as well
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, cherry-pick-this-to-main

#2160 Clarify that CREATE OR REPLACE DB deletes indexes and constraints as well (#2154)
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: cherry-picked, main

#2161 Clarify that CREATE OR REPLACE DB deletes indexes and constraints as well (#2154)
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: cherry-picked, 5.x

#2155 Add info about the `queryLang` field
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-main

#2162 Add info about the `queryLang` field (#2155)
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, main

#2164 Change Cypher syntax for administration commands to Database management command syntax
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2166 Change Cypher syntax for administration commands to Database management command syntax (#2164)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: cherry-picked

#2167 Change Cypher syntax for administration commands to Database management command syntax (#2164)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: cherry-picked, 5.x

#2169 Update the command for running cypher shell in a pod to access a cluster
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2171 Update the command for running cypher shell in a pod to access a cluster (#2169)
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
Labels: cherry-picked, 5.x

#2170 Update the command for running cypher shell in a pod to access a cluster (#2169)
  modules/ROOT/pages/kubernetes/quickstart-cluster/access-inside-k8s.adoc
Labels: cherry-picked

#2172 Update setting up analytical cluster with GDS plugin on Kubernetes
  modules/ROOT/pages/kubernetes/quickstart-analytics-cluster.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2168 Update dump/load that for CE you must stop the whole DBMS
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2175 Update dump/load that for CE you must stop the whole DBMS (#2168)
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: cherry-picked

#2176 Update dump/load that for CE you must stop the whole DBMS (#2168)
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
Labels: cherry-picked, 5.x

#2178 Add new settings to support custom endpoints in Azure COSI
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: This branch only, 5.26.4

#2179 Bump exact version number to 5.26.4
  antora.yml
Labels: This branch only, 5.26.4

#2181 Document updated descriptions of some Raft metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 2025.03

#2177 Document update/change/delete in block format incremental import
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-main

#2182 Document update/change/delete in block format incremental import (#2177)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked

#2180 Add new configuration settings and update the default of `server.metrics.filter`
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/dynamic-settings.adoc
Labels: 2025.03

#2165 Documentation for TLS certificate rotation feature
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/procedures.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: dev, 2025.03

#2187 Add xref to the cloud integration settings
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 2025.03

#2188 Bump version number to 4.4.42
  antora.yml
Labels: 4.4, This branch only

#2186 Clarify that a recreate won't keep read availability.
  modules/ROOT/pages/clustering/disaster-recovery.adoc
Labels: cherry-pick-this-to-5.x, dev, clustering, cherry-pick-this-to-main

#2190 Clarify that a recreate won't keep read availability. (#2186)
  modules/ROOT/pages/clustering/disaster-recovery.adoc
Labels: cherry-picked, main

#2191 Clarify that a recreate won't keep read availability. (#2186)
  modules/ROOT/pages/clustering/disaster-recovery.adoc
Labels: cherry-picked, 5.x

#2194 Add a note on deprecation of `standard` and `high_limit`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2197 Add a note on deprecation of `standard` and `high_limit` (#2194)
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, 5.x

#2195 Fix cloud URIs
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2198 Fix cloud URIs (#2195)
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, main

#2199 Fix the cloud URIs
  modules/ROOT/pages/clustering/databases.adoc
Labels: 5.x, This branch only

#2193 Clarify the difference between copying and overwriting TLS certificates
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: 2025.03

#2202 Add a note about the configs for Azure deployments
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.x, This branch only

#2201 Turn examples into sections
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, cherry-pick-this-to-main

#2206 Turn examples into sections (#2201)
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
Labels: cherry-picked, main

#2207 Turn examples into sections (#2201)
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
Labels: cherry-picked, 5.x
