Repository neo4j/docs-operations, pull requests merged in 2025-06, with the labels that each got.

#2379 Clarify database health status (#2370)
  modules/ROOT/pages/clustering/monitoring/endpoints.adoc
Labels: cherry-picked, 5.x

#2380 Clarify database health status
  modules/ROOT/pages/monitoring/causal-cluster/http-endpoints.adoc
Labels: 4.4, copied

#2208 Update Azure SSO tutorial
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2388 Update Azure SSO tutorial (#2208)
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked

#2389 Update Azure SSO tutorial (#2208)
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked

#2390 Clarify that ALTER DATABASES cannot be used for changing the store format of a database
  modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2392 Clarify that ALTER DATABASES cannot be used for changing the store format of a database (#2390)
  modules/ROOT/pages/database-administration/standard-databases/alter-databases.adoc
Labels: cherry-picked

#2397 Update version to 2025.06
  antora.yml
Labels: 2025.06

#2398 Move the recreate procedure to a separate page (#2367)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  modules/ROOT/pages/database-administration/standard-databases/recreate-database.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, main

#2394 Change the titles of all tutorials to be consistent
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2402 Change the titles of all tutorials to be consistent (#2394)
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/docker/clustering.adoc
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/tutorial-clustering-docker.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-picked

#2382 Tweak the Seed from URI page in 5.x
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Labels: 5.x, This branch only

#2395 Explain list handling differences between Parquet and CSV
  modules/ROOT/pages/import.adoc
Labels: cherry-pick-this-to-main

#2386 Improve docs around lost updates
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, team-kernel

#2412 Improve docs around lost updates (#2386)
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
Labels: cherry-picked

#2411 Improve docs around lost updates (#2386)
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
Labels: cherry-picked

#2415 Add valid options of the `queryLang` field
  modules/ROOT/pages/monitoring/logging.adoc
Labels: Cypher 25, cypher-25-branch

#2416 Add the label `introduced` to the `--idle-timeout` arg
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: 5.x, This branch only

#2417 Move the recreate procedure to the separate page in 5.x
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  modules/ROOT/pages/database-administration/standard-databases/recreate-database.adoc
  modules/ROOT/pages/procedures.adoc
Labels: 5.x, This branch only, copied

#2418 Clarify Cypher 25 change to propertyTypes return column
  modules/ROOT/pages/procedures.adoc
Labels: Cypher 25

#2425 Clarify how to recreate a db using the empty list of seeding servers
  modules/ROOT/pages/database-administration/standard-databases/recreate-database.adoc
Labels: cherry-pick-this-to-5.x, auto-cherry-pick, auto-cherry-pick-to-main

#2423 Change the default error format for Cypher Shell
  modules/ROOT/pages/cypher-shell.adoc
Labels: 2025.06

#2439 Update deprecations and removals for the June release
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: Cypher 25, 2025.06

#2446 added RHEL 9.6 to supported OS table
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-pick-this-to-5.x, dev, auto-cherry-pick, auto-cherry-pick-to-main

#2448 Update deprecations and removals for the June release (#2439)
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: cherry-picked, cypher-25-branch

#2449 added RHEL 9.6 to supported OS table (#2446)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, main

#2454 Add `dbms.routing.load_balancing.config.server_policies` to the configs reference page (#2414)
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, main

#2456 Add `dbms.routing.load_balancing.config.server_policies` to the confi…
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked, cypher-25-branch
