Repository neo4j/docs-operations, pull requests merged in 2025-04, with the labels that each got.

#2033 Disallow unquoted database names with dot
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
Labels: DO NOT MERGE, Cypher 25

#2218 Bump the version number to 5.26.5
  antora.yml
Labels: 5.x, This branch only

#2009 Update REVOKE information to say that in cypher 25 you get errors for impossible revoke commands
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/manage-roles.adoc
Labels: team-cypher-operations, Cypher 25

#2215 Fix the link to the Cypher manual
  modules/ROOT/pages/clustering/seed.adoc
Labels: 4.4, This branch only

#2132 Updates to CREATE DATABASE for Cypher 25
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: DO NOT MERGE, dev, team-cypher-operations, clustering, Cypher 25

#2223 Split the codeblock in the RPM install page
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2224 Split the codeblock in the RPM install page (#2223)
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: cherry-picked, main

#2216 Add optional SET keyword for create database clauses in Cypher 25
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: team-cypher-operations, Cypher 25

#2225 Split the code block
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: 5.x, This branch only

#2213 Strip Tools section out and put the pages in the relevant places
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/authentication-authorization/password-and-user-recovery.adoc
  modules/ROOT/pages/backup-restore/aggregate.adoc
  modules/ROOT/pages/backup-restore/consistency-checker.adoc
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/index.adoc
  modules/ROOT/pages/backup-restore/inspect.adoc
  modules/ROOT/pages/backup-restore/offline-backup.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/backup-restore/restore-dump.adoc
  modules/ROOT/pages/clustering/clustering-advanced/index.adoc
  modules/ROOT/pages/clustering/clustering-advanced/unbind.adoc
  modules/ROOT/pages/clustering/disaster-recovery.adoc
  modules/ROOT/pages/clustering/index.adoc
  modules/ROOT/pages/configuration/command-expansion.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/index.adoc
  modules/ROOT/pages/configuration/migrate-configuration.adoc
  modules/ROOT/pages/configuration/neo4j-admin-memrec.adoc
  modules/ROOT/pages/configuration/validate-config.adoc
  modules/ROOT/pages/cypher-shell.adoc
  modules/ROOT/pages/database-administration/queries.adoc
  modules/ROOT/pages/database-administration/standard-databases/migrate-database.adoc
  modules/ROOT/pages/database-administration/standard-databases/upload-to-aura.adoc
  modules/ROOT/pages/database-internals/index.adoc
  modules/ROOT/pages/database-internals/neo4j-admin-store-info.adoc
  modules/ROOT/pages/database-internals/store-formats.adoc
  modules/ROOT/pages/docker/operations.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/kubernetes/import-data.adoc
  modules/ROOT/pages/monitoring/index.adoc
  modules/ROOT/pages/monitoring/neo4j-admin-report.adoc
  modules/ROOT/pages/neo4j-admin-neo4j-cli.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/tools/index.adoc
  modules/ROOT/pages/tutorial/neo4j-admin-import.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: cherry-pick-this-to-main

#2203 Move the content on seed from URI to a new page
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2212 Update column info for show databases to mention where composite databases return null
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, 2025.04, cherry-pick-this-to-cypher-25

#2229 Update column info for show databases to mention where composite databases return null (#2212)
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Labels: cherry-picked

#2228 Update column info for show databases to mention where composite databases return null (#2212)
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
Labels: cherry-picked, 5.x

#2210 Deprecate `dbms.cluster.recreateDatabase`
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/procedures.adoc
Labels: 2025.04, cherry-pick-this-to-cypher-25

#2236 Fix a broken link to the K8s official docs (#2214)
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: cherry-picked

#2234 Fix a broken link to the K8s official docs (#2214)
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: cherry-picked

#2238 Update the examples of display store information (#2231)
  modules/ROOT/pages/database-internals/neo4j-admin-store-info.adoc
Labels: cherry-picked

#2239 Update the examples of display store information (#2231)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
Labels: cherry-picked

#2240 Update store info examples
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-store-info.adoc
Labels: 5.x

#2241 Move the content on seed from URI to a new page (#2203)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Labels: cherry-picked, main

#2242 Move the content on seed from URI to a new page (#2203)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Labels: cherry-picked, 5.x

#2232 Sync the `cypher-25` branch with the `dev`
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/backup-restore/planning.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/cypher-shell.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/delete-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
  publish.yml
Labels: This branch only, cypher-25-branch

#2244 Deprecate `dbms.cluster.recreateDatabase` (#2210)
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, cypher-25-branch

#2185 Update Okta examples
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2248 Update Okta examples (#2185)
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked

#2249 Update Okta examples (#2185)
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked

#2250 Update Okta examples (#2185)
  modules/ROOT/pages/tutorial/index.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked

#2252 Add a note about the automatic group_to_role_mapping being disabled (#2233)
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Labels: cherry-picked

#2253 Add a note about the automatic group_to_role_mapping being disabled (#2233)
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Labels: cherry-picked

#2254 Add a note about the automatic group_to_role_mapping being disabled (#2233)
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
Labels: cherry-picked

#2245 Document a new option `--prefer-diff-as-parent`
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: 2025.04, cherry-pick-this-to-cypher-25

#2256 Document a new option `--prefer-diff-as-parent` (#2245)
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-picked, cypher-25-branch

#2259 How to remove a server from the cluster on AWS (#2217)
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
Labels: cherry-picked, main

#2260 How to remove a server from the cluster on AWS (#2217)
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
Labels: cherry-picked, cypher-25-branch

#2261 How to remove a server from the cluster on AWS (#2217)
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
Labels: cherry-picked, 5.x

#2255 Relationship PBAC
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
Labels: team-cypher-operations, 2025.04

#2262 Document --temp-path for import
  modules/ROOT/pages/import.adoc
Labels: 2025.04

#2263 Document max-off-heap-memory and the deprecation of --pagecache
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/database-administration/standard-databases/migrate-database.adoc
Labels: 2025.04

#2265 Database alias can now be used as default database
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/procedures.adoc
Labels: 2025.04

#2267 Document --error-format argument to Cypher Shell
  modules/ROOT/pages/cypher-shell.adoc
Labels: 2025.04

#2268 Document --temp-path for import (#2262)
  modules/ROOT/pages/import.adoc
Labels: cherry-picked

#2269 Document max-off-heap-memory and the deprecation of --pagecache (#2263)
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/database-administration/standard-databases/migrate-database.adoc
Labels: cherry-picked

#2270 Database alias can now be used as default database (#2265)
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked

#2271 Document --error-format argument to Cypher Shell (#2267)
  modules/ROOT/pages/cypher-shell.adoc
Labels: cherry-picked

#2272 Bump express from 4.21.2 to 5.1.0 in the dev-dependencies group (#2209)
  package.json
Labels: cherry-picked

#2266 Fix the path and name of the `metadata_script.cypher`
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2273 Fix the path and name of the `metadata_script.cypher` (#2266)
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, cypher-25-branch

#2274 Fix the path and name of the `metadata_script.cypher` (#2266)
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, main

#2275 Fix the path and name of `metadata_script.cypher` (#2266)
  modules/ROOT/pages/authentication-authorization/manage-users.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, 5.x

#2277 Fix the path and name of metadata_script.cypher
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/tutorial/causal-backup-restore-db.adoc
Labels: 4.4, This branch only

#2264 Document how many days ago the license expired
  modules/ROOT/pages/neo4j-admin-neo4j-cli.adoc
Labels: 2025.04, cherry-pick-this-to-cypher-25

#2279 Add new CDC procedure `db.cdc.translateId`
  modules/ROOT/pages/procedures.adoc
Labels: 2025.04, cherry-pick-this-to-cypher-25

#2280 Add new CDC procedure `db.cdc.translateId` (#2279)
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, cypher-25-branch

#2258 Document the new clear data option for the recreate database procedure.
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/procedures.adoc
Labels: 2025.04, cherry-pick-this-to-cypher-25

#2282 Custom tx timeout can be set to any value
  modules/ROOT/pages/database-internals/transaction-management.adoc
Labels: cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2285 Custom tx timeout can be set to any value (#2282)
  modules/ROOT/pages/database-internals/transaction-management.adoc
Labels: cherry-picked, cypher-25-branch

#2284 Main tx timeout
  modules/ROOT/pages/database-internals/transaction-management.adoc
Labels: cherry-picked, main

#2292 Add tempDir to the aggregate command in K8s
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2294 Add tempDir to the aggregate command in K8s (#2292)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, main

#2295 Add tempDir to the aggregate command in K8s (#2292)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, Cypher 25

#2296 Add tempDir to the aggregate command in K8s (#2292)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#2293 Fix formatting issue due to missing `
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
Labels: cherry-pick-this-to-5.x, dev, team-cypher-operations, cherry-pick-this-to-cypher-25

#2297 Fix formatting issue due to missing ` (#2293)
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
Labels: cherry-picked, main

#2298 Fix formatting issue due to missing ` (#2293)
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
Labels: cherry-picked, 5.x

#2288 Document metrics reporting -1 on block format.
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25, team-kernel

#2286 Explain the use of `prefer-diff-as-parent`
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: 2025.04, cherry-pick-this-to-cypher-25

#2300 Explain the use of `prefer-diff-as-parent` (#2286)
  modules/ROOT/pages/backup-restore/online-backup.adoc
Labels: cherry-picked, cypher-25-branch

#2291 Reword the note about creating a database after restoring a CDC enabled database
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main, cherry-pick-this-to-cypher-25

#2301 Reword the note about creating a database after restoring a CDC enabled database (#2291)
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, main

#2302 Reword the note about creating a database after restoring a CDC enabled database (#2291)
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, cypher-25-branch

#2303 Reword the note about creating a database after restoring a CDC enabled database (#2291)
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: cherry-picked, 5.x

#2304 2025.04 merge dev
  antora.yml
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/cypher-shell.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/listing-databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/migrate-database.adoc
  modules/ROOT/pages/import.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/neo4j-admin-neo4j-cli.adoc
  modules/ROOT/pages/procedures.adoc
  package.json
Labels: This branch only

#2305 Update version to 2025.05
  antora.yml
Labels: dev
