Repository neo4j/docs-operations, pull requests merged in 2025-01, with the labels that each got.

#2040 updated example output from an incorrect plugin request.
  modules/ROOT/pages/docker/plugins.adoc
Labels: cherry-pick-this-to-5.x

#1953 Add metrics for Raft Snapshots. Attempt/success/fail
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: clustering, 2025.01

#2016 You should list system primaries in your endpoints
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.x, cherry-pick-this-backward

#2011 Create or replace with seed from uri
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
Labels: dev, 2025.01

#2036 Remove deprecated and removed Cluster metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 2025.01

#2041 updated example output from an incorrect plugin request. (#2040)
  modules/ROOT/pages/docker/plugins.adoc
Labels: cherry-picked, 5.x

#2038 Remove the documentation updates section for Neo4j 5
  modules/ROOT/pages/index.adoc
Labels: 2025.01

#2034 Update the versioning section
  modules/ROOT/pages/introduction.adoc
Labels: 2025.01

#2044 Label Raft snapshots metrics as new
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 2025.01

#2042 Add description for the fields of recreateDatabase procedure
  modules/ROOT/pages/procedures.adoc
Labels: documentation, clustering, 2025.01

#2043 Add CPU usage metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 2025.01

#2047 Update exact version to 5.26.1
  antora.yml
Labels: 5.x, This branch only

#2049 Remove `dbms.setDatabaseAllocator()`
  modules/ROOT/pages/procedures.adoc
Labels: 2025.01

#2048 Replace `<prefix>.store.size.total` with `<prefix>.store.size.full`
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: 2025.01

#2051 updated system requirements to remove deprecated OSs
  modules/ROOT/pages/installation/requirements.adoc
Labels: 2025.01

#2002 Add seed restore until section and remove 5.x seed provider info
  modules/ROOT/pages/clustering/databases.adoc
Labels: clustering, 2025.01

#2055 updated 5.26 linux install instructions to move the repository links
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: 5.x, This branch only

#2054 updated install instructions for jdk 21 and new apt/dnf repository branches
  modules/ROOT/pages/installation/linux/debian.adoc
  modules/ROOT/pages/installation/linux/rpm.adoc
Labels: 2025.01

#2057 Clarify that you have to list system primaries in your endpoints
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: do not cherry-pick

#2062 Update the `neo4j-admin backup aggregate` command
  modules/ROOT/pages/backup-restore/aggregate.adoc
Labels: 2025.01

#2065 Add a line before the heading
  modules/ROOT/pages/clustering/databases.adoc
Labels: do not cherry-pick

#2063 Update the logging page for 2025.01
  modules/ROOT/pages/monitoring/logging.adoc
Labels: kernel, 2025.01

#2061 Remove mentions of Neo4j v5
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
  modules/ROOT/pages/tutorial/tutorial-composite-database.adoc
Labels: 2025.01

#2056 Update configuration settings for 2025.01
  modules/ROOT/pages/backup-restore/online-backup.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/dynamic-settings.adoc
  modules/ROOT/pages/docker/ref-settings.adoc
  modules/ROOT/pages/tools/neo4j-admin/migrate-configuration.adoc
Labels: 2025.01

#2052 updated system requirements to remove deprecated OSs
  modules/ROOT/pages/installation/requirements.adoc
Labels: 5.x

#2064 Document executionPlanCacheKeyHash and executableQueryCacheHit
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-pick-this-to-5.x

#2069 Document executionPlanCacheKeyHash and executableQueryCacheHit (#2064)
  modules/ROOT/pages/monitoring/logging.adoc
Labels: cherry-picked, 5.x

#2072 Remove mentions of fabric and update composite databases concepts page
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
Labels: 2025.01, team-cypher-composite

#2074 Java 17 leftovers
  modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: 2025.01

#2067 Fix links to Cypher Manual
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/authentication-authorization/load-privileges.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
  modules/ROOT/pages/authentication-authorization/property-based-access-control.adoc
  modules/ROOT/pages/clustering/databases.adoc
  modules/ROOT/pages/clustering/setup/routing.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/file-locations.adoc
  modules/ROOT/pages/configuration/plugins.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-composite-databases.adoc
  modules/ROOT/pages/database-administration/aliases/manage-aliases-standard-databases.adoc
  modules/ROOT/pages/database-administration/aliases/naming-aliases.adoc
  modules/ROOT/pages/database-administration/aliases/remote-database-alias-configuration.adoc
  modules/ROOT/pages/database-administration/composite-databases/querying-composite-databases.adoc
  modules/ROOT/pages/database-administration/routing-decisions.adoc
  modules/ROOT/pages/database-administration/standard-databases/naming-databases.adoc
  modules/ROOT/pages/database-internals/concurrent-data-access.adoc
  modules/ROOT/pages/database-internals/transaction-management.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/monitoring/query-management.adoc
  modules/ROOT/pages/performance/index-configuration.adoc
  modules/ROOT/pages/performance/memory-configuration.adoc
  modules/ROOT/pages/performance/statistics-execution-plans.adoc
  modules/ROOT/pages/procedures.adoc
  modules/ROOT/pages/security/checklist.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 2025.01

#2076 5.x backup support generic s3 endpoints
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#2077 Document neo4j-admin-exception-trace-DATETIME.log and neo4j-admin-import-DATETIME.log
  modules/ROOT/pages/monitoring/logging.adoc
Labels: 2025.01

#2071 Update Migrate a database page
  modules/ROOT/pages/tools/neo4j-admin/migrate-database.adoc
Labels: kernel, 2025.01

#2082 Remove CE from cloud deployments
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
Labels: 5.x

#2081 Remove CE from cloud deployments and prepare for 2025.01
  modules/ROOT/pages/cloud-deployments/neo4j-aws.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-azure.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
Labels: 2025.01

#2053 Add a new page for deprecations, removals, and changes per version
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/clustering/servers.adoc
Labels: 2025.01

#2080 Mention the `backup` category of `neo4j-admin` cmds in the index page
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
Labels: 5.x, do not cherry-pick

#2079 Change the default of `dbms.cypher.infer_schema_parts` back to `OFF`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 2025.01

#2060 Update Netty-TCNative for 2025.01 and other updates
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/configuration/ports.adoc
  modules/ROOT/pages/docker/security.adoc
  modules/ROOT/pages/security/checklist.adoc
  modules/ROOT/pages/security/ssl-framework.adoc
Labels: Dependencies w. other PR, 2025.01

#2083 Fix the anchor of `db.clearQueryCaches()`
  modules/ROOT/pages/procedures.adoc
Labels: cherry-pick-this-to-5.x

#2084 Fix the anchor of `db.clearQueryCaches()` (#2083)
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, 5.x

#2070 Update the Migrate configs page
  modules/ROOT/pages/tools/neo4j-admin/migrate-configuration.adoc
Labels: kernel, 2025.01

#2078 Update the table on neo4j-admin commands
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
Labels: 2025.01

#2085 Remove beta label from CDC
  modules/ROOT/pages/introduction.adoc
Labels: 5.x, do not cherry-pick

#2068 Add missing options of the copy and incremental import commands
  modules/ROOT/pages/backup-restore/copy-database.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 2025.01
