Repository neo4j/docs-operations, pull requests merged in 2025-08, with the labels that each got.

#2519 Update the exact version to 5.26.10
  antora.yml
Labels: 5.x, This branch only

#2520 Clarify seed from a URI that dumps can also be used as seeds (#2509)
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Labels: cherry-picked

#2522 Clarify that consistency check is not supported for diff backups (#2515)
  modules/ROOT/pages/backup-restore/consistency-checker.adoc
Labels: cherry-picked, main

#2523 Clarify seed from a URI that dumps can also be used as seeds (#2509)
  modules/ROOT/pages/database-administration/standard-databases/seed-from-uri.adoc
Labels: cherry-picked

#2526 remove 'open a support ticket' requirement with neo4j-admin database upload
  modules/ROOT/pages/database-administration/standard-databases/upload-to-aura.adoc
Labels: cherry-pick-this-to-main

#2531 remove 'open a support ticket' requirement with neo4j-admin database upload (#2526)
  modules/ROOT/pages/database-administration/standard-databases/upload-to-aura.adoc
Labels: cherry-picked

#2533 Fixes the rendering of some pages (#2532)
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked

#2534 Fixes the rendering of some pages (#2532)
  modules/ROOT/pages/clustering/setup/discovery.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: cherry-picked

#2525 First batch of refreshed images
  modules/ROOT/images/backup-chain-aggregation.svg
  modules/ROOT/images/cluster-on-k8s.svg
  modules/ROOT/images/federation-sharding.png
  modules/ROOT/images/federation-sharding.svg
  modules/ROOT/images/manage-dbs-community.png
  modules/ROOT/images/manage-dbs-community.svg
  modules/ROOT/images/manage-dbs-default.png
  modules/ROOT/images/manage-dbs-default.svg
  modules/ROOT/images/manage-dbs-enterprise.png
  modules/ROOT/images/manage-dbs-enterprise.svg
  modules/ROOT/images/remote-alias-overview.svg
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/server-setup.adoc
Labels: cherry-pick-this-to-main

#2539 First batch of refreshed images (#2525)
  modules/ROOT/images/backup-chain-aggregation.svg
  modules/ROOT/images/cluster-on-k8s.svg
  modules/ROOT/images/federation-sharding.png
  modules/ROOT/images/federation-sharding.svg
  modules/ROOT/images/manage-dbs-community.png
  modules/ROOT/images/manage-dbs-community.svg
  modules/ROOT/images/manage-dbs-default.png
  modules/ROOT/images/manage-dbs-default.svg
  modules/ROOT/images/manage-dbs-enterprise.png
  modules/ROOT/images/manage-dbs-enterprise.svg
  modules/ROOT/images/remote-alias-overview.svg
  modules/ROOT/pages/database-administration/composite-databases/concepts.adoc
  modules/ROOT/pages/database-administration/index.adoc
  modules/ROOT/pages/kubernetes/quickstart-cluster/server-setup.adoc
Labels: cherry-picked

#2490 Add documentation for the alter database privileges on database level
  modules/ROOT/images/privileges_grant_and_deny_syntax_database_privileges.svg
  modules/ROOT/images/privileges_hierarchy_database.svg
  modules/ROOT/pages/authentication-authorization/database-administration.adoc
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
Labels: team-cypher-operations, 2025.08

#2543 Update the description of the history option
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/cypher-shell.adoc
Labels: 2025.08

#2512 Add tabbed examples for multiple node IDs
  modules/ROOT/pages/import.adoc
Labels: cherry-pick-this-to-main, team-kernel

#2537 Document the configuration settings introduced for the Unix Domain Socket connector
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 2025.08

#2538 Fix the broken links
  modules/ROOT/pages/authentication-authorization/dbms-administration.adoc
  modules/ROOT/pages/authentication-authorization/limitations.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/configuration/neo4j-conf.adoc
  modules/ROOT/pages/database-administration/standard-databases/create-databases.adoc
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
  modules/ROOT/pages/procedures.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-pick-this-to-main

#2548 Fix broken links
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/monitoring/metrics/essential.adoc
  modules/ROOT/pages/performance/index-configuration.adoc
  modules/ROOT/pages/procedures.adoc
Labels: cherry-pick-this-to-main

#2550 Fix broken links (#2548)
  modules/ROOT/pages/authentication-authorization/built-in-roles.adoc
  modules/ROOT/pages/introduction.adoc
  modules/ROOT/pages/monitoring/metrics/essential.adoc
  modules/ROOT/pages/performance/index-configuration.adoc
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, main

#2521 Clarify backup/restore strategy regarding system db
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2555 Clarify backup/restore strategy regarding system db (#2521)
  modules/ROOT/pages/backup-restore/planning.adoc
Labels: cherry-picked, 5.x
