Repository neo4j/docs-operations, pull requests merged in 2025-02, with the labels that each got.

#2094 bump version to 4.4.41
  antora.yml
Labels: 4.4

#2091 Discovery v2 - hightlight port change
  modules/ROOT/pages/clustering/setup/discovery.adoc
Labels: 5.x, do not cherry-pick

#2092 Update the TAR/ZIP steps to include decoupling of files from binaries
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-pick-this-to-5.x

#2096 Update the TAR/ZIP steps to include decoupling of files from binaries (#2092)
  modules/ROOT/pages/installation/linux/tarball.adoc
  modules/ROOT/pages/installation/osx.adoc
  modules/ROOT/pages/installation/windows.adoc
Labels: cherry-picked, 5.x

#2073 Update the intro page for 5.x series
  modules/ROOT/pages/index.adoc
Labels: 5.x, do not cherry-pick, 2025.01

#2097 bump version to 5.26.2
  antora.yml
Labels: 5.x

#2098 update publish.yml file
  publish.yml
Labels: dev

#2100 Small typo fix on start page
  modules/ROOT/pages/index.adoc
Labels: cherry-pick-this-to-main

#2101 Small typo fix on start page (#2100)
  modules/ROOT/pages/index.adoc
Labels: cherry-picked

#2090 Update the restore command
  modules/ROOT/pages/backup-restore/restore-backup.adoc
Labels: clustering, 2025.02

#2102 Add links to the Components of the graph privilege commands from where HOME GRAPH is mentioned
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, cherry-pick-this-to-main

#2093 Emphasize in docs that in clustering environments, when using incremental import the updated database must be reseeded
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2106 Add links to the Components of the graph privilege commands from where HOME GRAPH is mentioned (#2102)
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: cherry-picked

#2107 Add links to the Components of the graph privilege commands from where HOME GRAPH is mentioned (#2102)
  modules/ROOT/pages/authentication-authorization/manage-privileges.adoc
  modules/ROOT/pages/authentication-authorization/privileges-reads.adoc
  modules/ROOT/pages/authentication-authorization/privileges-writes.adoc
  modules/ROOT/pages/database-administration/syntax.adoc
Labels: cherry-picked

#2104 Update the discovery settings for the 5.26.2 release
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: 5.x, do not cherry-pick

#2105 Update the description of `update-all-matching-relationships`
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 2025.02

#2110 Emphasize in docs that in clustering environments, when using incremental import the updated database must be reseeded (#2093)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked

#2109 Emphasize in docs that in clustering environments, when using incremental import the updated database must be reseeded (#2093)
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: cherry-picked

#2112 Fix the Configure the thread pool for a Bolt connector example to show minimum size 5 as it is in the description (#2103)
  modules/ROOT/pages/performance/bolt-thread-pool-configuration.adoc
Labels: cherry-picked

#2111 Fix the Configure the thread pool for a Bolt connector example to show minimum size 5 as it is in the description (#2103)
  modules/ROOT/pages/performance/bolt-thread-pool-configuration.adoc
Labels: cherry-picked

#2099 bump version to 2025.02
  antora.yml
  package.json
  preview.yml
  publish.yml
Labels: 2025.02

#2087 Add setting for disabling raft async acquisition
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: clustering, 2025.02

#2088 Add metrics for inbound queue in raft
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: clustering, 2025.02

#2046 Add store copy metrics
  modules/ROOT/pages/monitoring/metrics/reference.adoc
Labels: clustering, 2025.02

#2114 Add missing aliases
  modules/ROOT/pages/authentication-authorization/index.adoc
  modules/ROOT/pages/cloud-deployments/neo4j-gcp.adoc
  modules/ROOT/pages/clustering/monitoring/show-databases-monitoring.adoc
  modules/ROOT/pages/clustering/setup/deploy.adoc
  modules/ROOT/pages/database-administration/routing-decisions.adoc
  modules/ROOT/pages/database-internals/transaction-management.adoc
  modules/ROOT/pages/docker/backup-restore.adoc
  modules/ROOT/pages/docker/dump-load.adoc
  modules/ROOT/pages/kubernetes/accessing-neo4j.adoc
  modules/ROOT/pages/procedures.adoc
  modules/ROOT/pages/tools/neo4j-admin/index.adoc
  modules/ROOT/pages/tutorial/access-control.adoc
Labels: 5.x

#2120 Fix the config name `dbms.cluster.raft.async_channel_acquisition_enabled`
  modules/ROOT/pages/configuration/configuration-settings.adoc
Labels: clustering, 2025.02

#2123 Add missing alias
  modules/ROOT/pages/clustering/clustering-advanced/multi-data-center-routing.adoc
Labels: 5.x, This branch only

#2125 Add info about the server-logs.xml file
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2127 Add info about the server-logs.xml file (#2125)
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked, 5.x

#2128 Add info about the server-logs.xml file (#2125)
  modules/ROOT/pages/authentication-authorization/sso-integration.adoc
  modules/ROOT/pages/monitoring/logging.adoc
  modules/ROOT/pages/tutorial/tutorial-sso-configuration.adoc
Labels: cherry-picked, main

#2124 Improve the 5th level headings
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2129 Improve the 5th level headings (#2124)
  modules/ROOT/pages/clustering/databases.adoc
Labels: cherry-picked, main

#2121 Add a line about Notification API
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: cherry-pick-this-to-main

#2130 Turn 5th level headings into the descr list
  modules/ROOT/pages/clustering/databases.adoc
Labels: 5.x

#2131 Add a line about Notification API (#2121)
  modules/ROOT/pages/changes-deprecations-removals.adoc
Labels: cherry-picked, main

#2135 Clarify the supported filesystems for Linux (#2122)
  modules/ROOT/pages/installation/requirements.adoc
Labels: cherry-picked, main

#2136 Clarify the supported filesystems for Linux (#2122)
  modules/ROOT/pages/installation/requirements.adoc
Labels: 4.4, cherry-picked

#2126 Update cypher-shell.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: cherry-picked, DO NOT MERGE

#2138 Update cypher-shell.adoc
  modules/ROOT/pages/tools/cypher-shell.adoc
Labels: cherry-picked, 5.x

#2137 Removed beta label from set vector property functions.
  modules/ROOT/pages/procedures.adoc
Labels: cherry-pick-this-to-dev

#2141 Removed beta label from set vector property functions. (#2137)
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked

#2119 Updates the hospital example to include steps on how to create and load the healthcare database
  models/hospital/README.txt
  models/hospital/access-control-old.adoc
  models/hospital/healthcare_config.sh
  models/hospital/healthcare_queries_broken.cypher
  models/hospital/healthcare_queries_doctor.cypher
  models/hospital/healthcare_queries_itadmin.cypher
  models/hospital/healthcare_queries_junior.cypher
  models/hospital/healthcare_queries_nurse.cypher
  models/hospital/healthcare_queries_receptionist.cypher
  models/hospital/healthcare_queries_researcherB.cypher
  models/hospital/healthcare_queries_researcherW.cypher
  models/hospital/healthcare_queries_userManager.cypher
  models/hospital/make_healthcare.cypher
  models/hospital/make_healthcare_meta.cypher
  models/hospital/run_roles.sh
  models/hospital/setup_healthcare.cypher
  models/hospital/setup_healthcare.sh
  models/hospital/setup_healthcare_privileges.cypher
  modules/ROOT/pages/tutorial/access-control.adoc
  modules/ROOT/pages/tutorial/index.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, cherry-pick-this-to-main

#2143 Updates the hospital example to include steps on how to create and load the healthcare database (#2119)
  models/hospital/README.txt
  models/hospital/access-control-old.adoc
  models/hospital/healthcare_config.sh
  models/hospital/healthcare_queries_broken.cypher
  models/hospital/healthcare_queries_doctor.cypher
  models/hospital/healthcare_queries_itadmin.cypher
  models/hospital/healthcare_queries_junior.cypher
  models/hospital/healthcare_queries_nurse.cypher
  models/hospital/healthcare_queries_receptionist.cypher
  models/hospital/healthcare_queries_researcherB.cypher
  models/hospital/healthcare_queries_researcherW.cypher
  models/hospital/healthcare_queries_userManager.cypher
  models/hospital/make_healthcare.cypher
  models/hospital/make_healthcare_meta.cypher
  models/hospital/run_roles.sh
  models/hospital/setup_healthcare.cypher
  models/hospital/setup_healthcare.sh
  models/hospital/setup_healthcare_privileges.cypher
  modules/ROOT/pages/tutorial/access-control.adoc
  modules/ROOT/pages/tutorial/index.adoc
Labels: cherry-picked

#2144 Updates the hospital example to include steps on how to create and load the healthcare database (#2119)
  models/hospital/README.txt
  models/hospital/access-control-old.adoc
  models/hospital/healthcare_config.sh
  models/hospital/healthcare_queries_broken.cypher
  models/hospital/healthcare_queries_doctor.cypher
  models/hospital/healthcare_queries_itadmin.cypher
  models/hospital/healthcare_queries_junior.cypher
  models/hospital/healthcare_queries_nurse.cypher
  models/hospital/healthcare_queries_receptionist.cypher
  models/hospital/healthcare_queries_researcherB.cypher
  models/hospital/healthcare_queries_researcherW.cypher
  models/hospital/healthcare_queries_userManager.cypher
  models/hospital/make_healthcare.cypher
  models/hospital/make_healthcare_meta.cypher
  models/hospital/run_roles.sh
  models/hospital/setup_healthcare.cypher
  models/hospital/setup_healthcare.sh
  models/hospital/setup_healthcare_privileges.cypher
  modules/ROOT/pages/tutorial/access-control.adoc
  modules/ROOT/pages/tutorial/index.adoc
Labels: cherry-picked, 5.x

#2139 Document --schema option for incremental import
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 2025.02

#2113 Improve the descriptions of --skip-bad-relationships, --skip-duplicate-nodes, and --update-all-matching-relationships
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
Labels: 2025.02

#2142 Fix beta and introduced labels for vector functions
  modules/ROOT/pages/procedures.adoc
Labels: 5.x, This branch only

#2145 Fix the link to the Vector functions page
  modules/ROOT/pages/procedures.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-main

#2148 Fix the link to the Vector functions page (#2145)
  modules/ROOT/pages/procedures.adoc
Labels: cherry-picked, 5.x

#2146 Add page alias to Fine-grained access control page
  modules/ROOT/pages/tutorial/access-control.adoc
Labels: 5.x, This branch only

#2150 Update the version in all K8s backup-restore examples to be the latest
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked

#2151 Update the version in all K8s backup-restore examples to be the latest (#2149)
  modules/ROOT/pages/kubernetes/operations/backup-restore.adoc
Labels: cherry-picked, 5.x

#2156 Update the neo4j-version-exact attribute in the antora.yml file
  antora.yml
Labels: This branch only, 5.26

#2157 Publish 2025.02
  antora.yml
  modules/ROOT/pages/backup-restore/restore-backup.adoc
  modules/ROOT/pages/changes-deprecations-removals.adoc
  modules/ROOT/pages/configuration/configuration-settings.adoc
  modules/ROOT/pages/monitoring/metrics/reference.adoc
  modules/ROOT/pages/tools/neo4j-admin/neo4j-admin-import.adoc
  package.json
  preview.yml
  publish.yml
Labels: This branch only

#2158 Update dev version to 2025.03
  antora.yml
Labels: 2025.03

#2159 Remove developer survey
  publish.yml
Labels: cherry-pick-this-to-main
